### PR TITLE
flyTo() events now firing only when appropiate.

### LINKED ISSUE #3134: flyTo generates many moveend events
Reported [here](https://github.com/mlevans/leaflet-hash/issues/38#issuecomment-69810963) and replicated with `debug/map/zoompan.html` (uncommenting the logging there for move events).

Expected behavior would be to emit a single moveend event when the animation completes or is canceled.

### PR DESCRIPTION
**Pull request by IvanSanchez**
Should fix #3134, even if the code is a tiny bit hackish IMHO.

### CODE REVIEW

**Comment by mourner** [comment]
Thanks! I rewrote the confusing logic in `_resetView` in #3278, I guess we need to coordinate the changes before I can merge this. Can you look at that PR and see if those changes make sense?

**Comment by IvanSanchez** [comment]
Let me rebase this into `events-refactor` and see how much stuff breaks down.

**Comment by mourner** [comment]
@IvanSanchez it will probably be easier to review the changes before rebasing, the latter would get confusing without background.

**Comment by IvanSanchez** [comment]
Not needed once #3278 gets merged, events are fired as expected in the `events-refactor` branch.

**Pull request closed without merging**
