### PR TITLE
Improve Leaflet website visual design & UX.

### PR DESCRIPTION
**Pull request by rowanhogan**
**Updates**
- Added persistent TOC menu for API docs page
- Responsive design for mobile/tablet
- Overall visual design & typography refresh whilst aiming for consistency with current site
- Added retina image assets and updated favicon
- Optimised image assets

The updates can be seen live at http://rowanhogan.github.io/Leaflet/

Leaflet API docs page - Desktop

**Rationale**
I've accessed the [reference docs](http://leafletjs.com/reference.html) many times in the past, and have found it's a very large and difficult page to navigate. I've always wished the API docs were as easy to use as the API itself!

I also wanted to contribute as a UI/UX designer to give the page a bit of a refresh, and improve the readability/usability on different devices. Please give me any feedback, I'm happy to make changes. :)

### CODE REVIEW

**Comment by mourner** [comment]
Wow, thanks a lot for working on this! Lots of great stuff here. Especially love the dynamic table of contents on the API docs page.

But for future, please don't put lots of effort in to a contribution before discussing it with project maintainers. In this case, there's already a mobile-friendly, more modern Leaflet website redesign branch (`redesign`), so we would have to discard a lot of the stylistic changes here, and port over some things to the branch. The latter is a bit old but I was going to pick it up again.

I'll follow up with more comments on Tuesday.

**Comment by rowanhogan** [comment]
Thanks @mourner!

Sorry I didn't realise there was already a new `redesign` branch (I was looking for anything else related to `gh-pages` before I started).

To be honest the visual design changes I made were actually very quick/minor despite the visual impact – I changed the typography and updated the headings etc. Most of my time was spent on the TOC menu for the API page and responsive fixes such as the tables as you mentioned. Also, I know I may have been a bit opinionated with the design direction, and my intention was to start a dialogue. :)

From having a look now at the redesign branch, a lot of what I changed can be added to that branch. See  attached screenshot for comparison of my updates (middle) versus the redesign branch (far left) and my updates in keeping with the redesign branch (e.g. using Open Sans, headings with green bg – far right).

screen shot 2015-06-29 at 9 00 53 am

Please note that the theme change for the code blocks wasn't just personal preference / design, but to add contrast from the tables to help them stand out as you scan the page. As I said I'm more than happy to make alterations and work with you and the Leaflet maintainers to improve the project.

If you like I can update this PR to only include responsive tables & API menu, and then merge with `redesign` and submit any further updates to that branch? Also please let me know any direction you were hoping to take with the `redesign` branch, I'm more than happy to help out with the upates – I've used _Leaflet.js_ extensively so I want to give something back!

**Comment by danzel** [comment]
:+1:
For what it is worth, I like the middle one from the screenshots above.

**Comment by mourner** [comment]
Exciting! Reviewed the changes in #3569. We can either merge just the ToC now, or just close this and quickly finish the `redesign` branch and merge it to save you some time.

**Comment by rowanhogan** [comment]
Yeah I'd rather press on with the `redesign` branch and help get those updates out.

**Pull request closed without merging**
