### PR TITLE
Removes an incorrect semicolon

### PR DESCRIPTION
**Pull request by mejackreed**

### CODE REVIEW

**Comment by perliedman** [comment]
:+1:  Thanks!

**Comment by IvanSanchez** [comment]
@mejackreed Did you check the comments in `src/layer/vector/Canvas.js`? The documentation is generated from those, and the misplaced/missing semicolon should have been fixed there instead.

**Comment by perliedman** [comment]
Oops, sorry, apparenly didn't check what file the change was in :disappointed:

**Comment by mejackreed** [comment]
Sorry no I did not check, but those appear to not have the semicolon. Removed here: https://github.com/Leaflet/Leaflet/commit/db7482a5619e1aa9c865870370b6500e85ef9c2c

**Comment by IvanSanchez** [comment]
Looks OK then. The documentation files (the whole `reference-1.0.0.html` file) will be overwritten in the next release anyway.

**Pull request merged**
