### PR TITLE
Switch to active fork of Leaflet.markercluster

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**

### CODE REVIEW

**Comment by jonkoops** [comment]
Since this is an extension on the Leaflet repository being replaced I don't think we want to merge this. While I acknowledge that currently our maintenance of plugins under our banner is not where it needs to be I think this is jumping the gun.

Closing this PR.

**Comment by KristjanESPERANTO** [comment]
Is there a plan to improve the situation? People have to deal with issues in the "official plugins" that have been fixed in some forks for a long time.

**Comment by jonkoops** [comment]
Submit a PR to fix those issues, we'll get to it when we can. Currently our main priorities are to work on Leaflet 2.0, the plugins will come later.

**Comment by KristjanESPERANTO** [comment]
Okay, this prioritization is understandable. Thank you for your work! 🙂

**Pull request closed without merging**
