### PR TITLE
Let's ship v1.3.0 release!

### PR DESCRIPTION
**Pull request by cherniavskii**
Hi,
I'd like to force new version release :)
A lot of bugfixes and improvements has been done since 1.2.0.

I wrote a changelog for new version.
There's a little incompatibility introduced by #5922, but I think we could release it as 1.3.0.

Would anybody have some time to publish new release soon?
cc @mourner @perliedman @IvanSanchez @ghybs 
  
- [x] Make a new release branch
- [x] Update [the changelog](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md) since last release and commit to the release branch
- [x] Write a blog post about the new release and put in `/docs/_posts` and commit to the release branch
- [x] Bump version number in `package.json` and commit to `master`
- [x] Make sure you do not have any `package.lock.json` or `yarn.lock` locally, since they can potentially make you build with the wrong package versions
- [x] Run `npm run release`
- Verify that the release was correctly published to NPM by checking:
  - [x] [Leaflet NPM package page](https://www.npmjs.com/package/leaflet)
  - [x] files on [Leaflet unpkg page](https://unpkg.com/leaflet@latest/)
- Update API docs:
  - [x] run `npm run docs`
  - [x] Copy the built docs from `dist/reference-X.Y.Z.html` to `docs/reference-X.Y.Z.html`
  - [x] Update the built docs header to use Jekyll style; see commit [11d716f0964d8bc0d058ca09e9ba8003451b4b8d](https://github.com/Leaflet/Leaflet/commit/11d716f0964d8bc0d058ca09e9ba8003451b4b8d) as reference for the needed changes
  - [x] Commit the new docs to the release branch
- [x] Update `docs/reference.html` to redirect to the new version and commit the change to the release branch
- Update integrity hashes:
  - [x] Checkout the release tag (`git checkout vX.Y.Z`)
  - [x] Run `npm run integrity` or simply `node ./build/integrity.js` if you're not on Debian
  - [x] Copy the hashes and update `integrity_hash_css`, `integrity_hash_source` and `integrity_hash_uglified` in `docs/_config.yml`; commit changes to the release branch
- [x] Update link to latest release in `docs/download.html`, and commit to the release branch
- [x] Add link to new version reference in `docs/reference-versions.html`, and commit to the release branch
- [x] Update `latest_leaflet_version` in `docs/_config.yml` and commit to the release branch
- [x] Update the "Latest news" section in `docs/index.html` and commit to the release branch
- [x] Update release date in changelog, blog post, announcement and other
- [x] If it looks like everything is good at this point, merge the release branch into `master`
- [ ] Make a new release on [Leaflet's GitHub release page](https://github.com/Leaflet/Leaflet/releases/) with the most important parts of the changelog

### CODE REVIEW

**Comment by perliedman** [comment]
@cherniavskii sounds like a plan! I think I can make some time for this on friday.

If you want to go ahead earlier than that, there's always https://github.com/Leaflet/Leaflet/blob/master/RELEASE.md with a checklist of the steps needed to make a release (or at least the steps I tried to follow for the last two).

**Comment by cherniavskii** [comment]
@perliedman yes, I'm going to go through those steps within the next few days.
But I need help at least with one step - publishing to NPM, so your help would be appreciated ;)

**Comment by cherniavskii** [comment]
Looks like I'm done on my side, since I don't have permission to publish new version to NPM.

@mourner may I ask for permission on NPM? Or should I wait for someone who has permission to publish new version?

**Comment by cherniavskii** [comment]
@mourner ping :)

**Comment by perliedman** [comment]
@cherniavskii sorry for not showing up yesterday.

 I _think_ I can add you as maintainer to the package, that makes most sense. Is your npm name "cherniavskii" ?

**Comment by perliedman** [comment]
@cherniavskii BTW, great work here - I know making a release is a lot of tedious work.

**Comment by cherniavskii** [comment]
@perliedman yes, my npm name is the same as github name :)

**Comment by perliedman** [comment]
@cherniavskii done!

**Comment by cherniavskii** [comment]
@perliedman thanks, I'll publish it tomorrow

**Pull request merged**
