### PR TITLE
International Date Line Crossing for Polylines and Polygons

### PR DESCRIPTION
**Pull request by briannaAndCo**
This is a path-rendering only fix that's an alternate proposal for fixing the existing issue where polygons and polylines that should wrap across the International Date Line instead wrap around the Prime Meridian.

Existing issues it addresses: 
Implemented polyline wrapping #5206
Proposal for solving "crossing date line geometries" problem #1293
Polygon Points across the dateline #2645

Tests have been added to handle the splitting algorithm
 and all existing tests pass.

internationaldatelinecrossing

### CODE REVIEW

**Comment by briannaAndCo** [comment]
Is this something that is still potentially desired?

**Comment by perliedman** [comment]
@briannaAndCo hi and thanks for submitting this. Like many of the other attempts to address this, my major concern is that this adds a lot of complexity and calculations to a somewhat performance critical code path.

While I appreciate that the anti-meridian _is_ an issue for many applications, it is also true that most Leaflet applications never have this problem, since features are local/small and most of the antimeridian is in remote areas and open ocean. I'm reluctant to add complexity and slower performance for _all_ Leaflet apps to address this particular problem.

Like many similar issues, I'm leaning towards recommending this as a plugin. Without having tested this particular approach, I think we would be happy to link to a plugin from our reference documentation for `Polyline` and `Polygon` for those that need to handle the antimeridian.

**Comment by briannaAndCo** [comment]
Agreed, that does sound like probably the optimal solution.

Is there a good resource that you know of for turning something like this into a plugin? That's something I haven't done before.

**Comment by cherniavskii** [comment]
@briannaAndCo here is a plugin guide, it will definitely help ;)
https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md

**Comment by briannaAndCo** [comment]
Awesome, thanks!

**Comment by perliedman** [comment]
@briannaAndCo I'm closing this PR for now, don't hesitate to poke us when/if you publish a plugin so that we could link to it if suitable.

**Pull request closed without merging**
