### PR TITLE
Remove check for webkitMobile before calling update on GridLayer._setView

### LINKED ISSUE #3659: Tiles not loading after setView on mobile
Tiles not loading If you open the following code to the mobile phone:
```javascript
var map = L.map('map', {
    center: [54.980206086231, 82.898068362003],
    zoom: 5
});

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

map.setZoom(9, {animate: false});
```

### PR DESCRIPTION
**Pull request by yohanboniface**
Fix #3659

I've not been able to spot any regression of https://github.com/Leaflet/Leaflet/commit/142e0661b190581c6e45c74c3419e46fdf98a5c5 so I'm pushing this for consideration.

@mourner do you remember any specific use case to check? Otherwise, I'm in favour of the "merge and see" workflow ;)

### CODE REVIEW

**Comment by mourner** [comment]
Let me check that on iOS.

**Comment by IvanSanchez** [comment]
Note that #3815 already removes this check and might cause a small merge conflict.

**Comment by yohanboniface** [comment]
Yep, just seen that. This PR will not be needed anymore when #3815 get merged.

**Comment by IvanSanchez** [comment]
#3815 got merged, so no need for this one.

**Pull request closed without merging**
