### PR TITLE
Have uglifyjs spit out a sourcemap for leaflet.js too.

### LINKED ISSUE #5341: Source map for minified leaflet.js
There is a source map for the non-minified leaflet-src.js, but nothing for the minified leaflet.js. Even if such a source map simply mapped back to leaflet-src.js rather than the "true" source I would still find it useful, as I'm sure would many others.

### PR DESCRIPTION
**Pull request by danzel**
Fixes #5341 
The resulting source map points back to the original files too :+1:

### CODE REVIEW

**Comment by danzel** [comment]
re my second commit.
I noticed that the resulting map file for `-src` is called `leaflet-src.js.map`, but the `publish.sh` file was adding `leaflet-src.map` (the 1.0.3 tagged build has `-src.map` as the file name).
Not sure if that was broken or what was going on, looks like it is a recent change.

**Comment by IvanSanchez** [comment]
@perliedman As I said in #5341 I don't really see the usefulness, but if you and @danzel agree, then it's OK.

**Comment by IvanSanchez** [comment]
Ah, oh, ok :smile: 

According to the [sourcemap spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.9ppdoan5f016):

> Optionally, a source map will have the same name as the generated file but with a “.map” extension.  For example, for “page.js” a source map named “page.js.map” would be generated. 

So ideally I'd go for `leaflet-src.js.map` and `leaflet.js.map`.

**Comment by IvanSanchez** [comment]
```
ivan@~/devel/Leaflet\ [pr/5351]$ ls -l dist                                                                                                              
total 1836                                                                                                                                                              
drwxr-xr-x 1 ivan ivan    146 des.  23 12:44 images
-rw-r--r-- 1 ivan ivan  13888 feb.   8 16:08 leaflet.css
-rw-r--r-- 1 ivan ivan 134439 feb.  21 13:41 leaflet.js
-rw-r--r-- 1 ivan ivan 617195 feb.  21 13:41 leaflet.js.map
-rw-r--r-- 1 ivan ivan 380727 feb.  21 13:41 leaflet-src.js
-rw-r--r-- 1 ivan ivan 725203 feb.  21 13:41 leaflet-src.js.map
```

LGTM.

**Pull request merged**
