### PR TITLE
Add leaflet-layer-overpass to plugins

### PR DESCRIPTION
**Pull request by k-nut**
I added a reference to the leaflet-layer-overpass library. If there is anything missing in the PR I will try to provide it as quick as possible.

### CODE REVIEW

**Comment by danzel** [comment]
This PR is conflicted, fixing that would be good thanks :)
Usually rebasing will fix this.

**Comment by k-nut** [comment]
I did not figure out how to rebase. I merged the newly added commit instead. Are you okay with that or should I try again?

**Comment by mourner** [comment]
It's OK, but I'd suggest learning to rebase as it's an invaluable tool! For your case, you can just do `git rebase origin/gh-pages`, then `git push --force`. It should remove "merge" commits automatically.

**Comment by k-nut** [comment]
I figured learning about reabse would be a good idea. I think I more or less understand how it works now. Thank you for pushing me into learning something new! I tried to rebase and it seems to have worked now! :sparkles:

**Comment by mourner** [comment]
Perfect!

**Pull request merged**
