### PR TITLE
Added 'use-credentials' Cors Option to ImageOverlay and TileLayer

### LINKED ISSUE #5891: Tile layer allows setting crossorigin true but doesn't let you set crossorigin property
## How to reproduce
Have a tile server that requires credentials 
- Leaflet version I'm using:1.2.0
- Browser (with version) I'm using:Firefox 45 and chrome 50

## What behaviour I'm expecting and which behaviour I'm seeing
Need to specify anonymous or use-credentials invalid or empty string is handled as anonymous per https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes

I can fork and make a PR if needed.

### PR DESCRIPTION
**Pull request by caleblogan**
Fixes  #5891 

I added a new option to set the crossOrigin property to 'use-credentials'. Another solution would be to make crossOrigin a String and set the default value to null. Let the user set crossOrigin as a String.

### CODE REVIEW

**Comment by ghybs** [comment]
Hi,

Thank you for contributing your first PR here!

I like that this new "`crossOriginCredentials`" option would make it easy to set the `crossorigin="use-credentials"` attribute and value.

Unfortunately it may conflict with the already existing [`crossOrigin`](http://leafletjs.com/reference-1.3.0.html#tilelayer-crossorigin) option; e.g. if we have:
```javascript
{
  crossOrigin: true,
  crossOriginCredentials: true
}
```
…the `` will have  the `crossorigin="use-credentials"` attribute and value (with current state of PR), although with `crossOrigin: true` we have requested to get `crossorigin=""`.

Furthermore, there are actually [3 possible states](https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-settings-attributes) for this attribute:
- `crossorigin="use-credentials"` => `"cors"` mode and `"include"` credentials mode.
- `crossorigin="anonymous"` (or actually any other value than `"use-credentials"`) => `"cors"` mode and `"same-origin"` credentials mode.
- no/omitted `crossorigin` attribute => `"no-cors"` mode.

Therefore we need at least a tristate option.

> Another solution would be to make crossOrigin a String

That would indeed match with @IvanSanchez's https://github.com/Leaflet/Leaflet/issues/5891#issuecomment-341361026

We could have:
- type `"string"` => `crossorigin="<crossOrigin-option-value>"`
- other truthy value => `crossorigin=""` (same effect as `crossorigin="anonymous"`)
- `false` (default) => no `crossorigin` attribute (`"no-cors"` requests mode)

This scheme would require the app developer to explicitly specify `crossOrigin: 'use-credentials'` option (instead of just `crossOriginCredentials: true`), but it leverages the already existing `crossOrigin` option and maintains backwards compatibility.

It also leaves this string out of the library (saves a few bytes for common case…), and keeps the door open to any other keyword that may appear in the future (how unlikely this may sound).

@IvanSanchez @cherniavskii what do you think?

**Comment by cherniavskii** [comment]
@ghybs I like proposition of `crossOrigin` accepting string - it's obvious and flexible.
Also, it's easy to refer `crossorigin` attribute docs in our documentation :)

**Comment by caleblogan** [comment]
I wasn't too sure how to phrase the docs. Especially the default value, String = false. I didn't do any type checking so setting crossOrigin=True will result in . This will still work, but I am not sure if it could cause a possible backwards compatibility problem.

**Comment by ghybs** [comment]
Thank you for the modification to make the PR now re-use the `crossOrigin` option! :+1: 

Even though the spec says that an invalid keyword (as `"true"` in this case) is interpreted as `"anonymous"` and `""` (empty string), it does not feel right that a currently valid option `crossOrigin: true` would then lead to using an invalid keyword.

Therefore I think we should at least convert `crossOrigin: true` to `crossorigin=""`.

As for the docs, you should specify that a Boolean type is possible, using a vertical pipe (`|`), like is done for the [`doubleClickZoom`](http://leafletjs.com/reference-1.3.0.html#map-doubleclickzoom) map option for example:
https://github.com/Leaflet/Leaflet/blob/ba6f97fff8647e724e4dfe66d2ed7da11f908989/src/map/handler/Map.DoubleClickZoom.js#L12-L17

**Pull request merged**
