### PR TITLE
Added support for fill patterns to be used in paths.

### PR DESCRIPTION
**Pull request by teastman**
I've attempted to add support for fill patterns [Issue #2214](https://github.com/Leaflet/Leaflet/issues/2214)

This is my first attempt at contributing to Leaflet core, so let me know if I did anything wrong, I haven't written any tests for the feature yet.

Usage example can be seen here http://jsfiddle.net/ehucL6v5/ I have no idea how to link my fork of leaflet.js in jsfiddle to show the example working though.

### CODE REVIEW

**Comment by mourner** [comment]
Hey, thanks for the pull request! While this is a very useful feature, it has just too many code to consider including it in Leaflet code given that the pattern use case isn't too common. But it would make for a wonderful plugin! What do you think?

**Comment by teastman** [comment]
Yeah plugin should work just fine.  I'll recode it as one, I was about to code it to work with 0.7.3 as well anyways.  Thanks for taking a look.

**Comment by mourner** [comment]
Thanks! Looking forward to it.

**Comment by teastman** [comment]
I've created a repo for a plugin to handle patterns and put it up at https://github.com/teastman/Leaflet.pattern
It's currently designed to work with 0.7.3

**Pull request closed without merging**
