### PR TITLE
Update documentation to change Haversines Formula to Spherical Law of…

### PR DESCRIPTION
**Pull request by loisgh**
I updated the documentation for the 1.2.0 version.  I was unsure if I should do this for the prior versions.  Please advise.

### CODE REVIEW

**Comment by loisgh** [comment]
Changed the pull request as per your comments.

**Comment by perliedman** [comment]
Thanks for jumping through all the hoops involved in making a PR! :+1:

**Comment by loisgh** [comment]
Thanks for giving me all the info I needed.

**Comment by Awfef** [comment]
24 Eyl 2017 19:46 tarihinde "Lois" <notifications@github.com> yazdı:

**Comment by Awfef** [comment]
/* ------------------------------------- 

		GLOBAL 

------------------------------------- */



* { 

	margin:0;

	padding:0;

}



.linksColorWhite a{color:#ffffff !important;text-decoration:none !important;}

.linksColorBlack a{color:#000000 !important;text-decoration:none !important;}

.linksColorGray a{color:#999999 !important;text-decoration:none !important;}





/* ------------------------------------- 

		END GLOBAL 

------------------------------------- */



table[class="bodyWidth"]{max-width:640px !important;}

td[class="bodyPadding"]{padding-left:50px !important;padding-right:50px !important;}

td[class="mobileHeadline"]{font-size:28px !important;}



@media only screen and (max-width: 415px) {



td[class="bodyPadding"]{padding-left:20px;padding-right:20px;}

table[class="cta"]{width:320px;}

td[class="mobileHeadline"]{font-size:26px !important;padding-left:20px;padding-right:20px;}





}



@media only screen 

and (min-device-width : 414px)

and (-webkit-min-device-pixel-ratio : 3) {

.zoomFix {height:85px !important;}

}











    

    

    	

         

    	

        

        

        Join Ebates for FREE to earn Cash Back + get a $10 welcome bonus.
        

        
  












Join Now

            
          

            







 
   
     
 Mehmet loves Ebates and thought you would, too. Join for free and enjoy Cash Back, awesome deals and more.
 


 

  

 
 

 

 

 
  
 


         














            

            

            

            

            

            	PRIVACY  

                 |   UNSUBSCRIBE

                

            

                        

            	© 2017 Ebates, Inc., 160 Spear St., 19th Fl., San Francisco, CA 94105

**Pull request merged**
