### PR TITLE
Linear zooming animation with overhauled scroll behavior

### LINKED ISSUE #2154: Zoom issues with Apple trackpad (Magic Mouse)
Zooming with the scroll gesture causes very jumpy behavior between zoom levels. The calls to `_performZoom` seem to add up, meaning the map keeps zooming after the user has stopped scrolling.

Basically the Apple trackpad creates A LOT of calls to `_onWheelScroll` and because of inertial scrolling, continues to call it after the user has actually stopped scrolling. For my uses, changing the value 

`var left = Math.max(40 - (+new Date() - this._startTime), 0);`

to something more like:

`var left = Math.max(200 - (+new Date() - this._startTime), 0);`

works decently. It makes the apple mouse a little too sensitive (harder to move between small numbers of zoom levels), but seems to get rid of the jumping effect. Any ideas of a better solution?

### PR DESCRIPTION
**Pull request by mourner**
This gives Leaflet zoom animation a very different feel, and should also solve all our problems with scroll wheel behavior. There was a similar attempt earlier, but this time, after recent tile loading and animation improvements, it feels much nicer. Tested both mouse and Macbook trackpad. Closes #2154, #2732, #2757.

@ChALkeR @moneytoo @CramericaIndustries @ekelleyv @robrecord @rossmeissl @mearsheimer @schovi @jfirebaugh @danzel I'd appreciate your feedback guys. How does the zoom feel in this branch?

Note: pretty broken in Safari (at least for me on OS X) atm.

### CODE REVIEW

**Comment by rossmeissl** [comment]
@wboykinm would you please take a look at this?

**Comment by wboykinm** [comment]
Actually it seems like it works best on safari with OSX :smiley_cat: 

## Chrome
linearzoom2_chrome

## Firefox
linearzoom2_ff

## Safari
linearzoom2_safari

**Comment by mourner** [comment]
@wboykinm so what do you think vs the old behavior?

**Comment by wboykinm** [comment]
@mourner I think the feel of the linear zoom is great, but I can't get the trackpad to behave right on chrome. The zoom gesture always double-zooms, no matter how faintly I touch it. The scrollwheel on my external mouse single-zooms as expected.

linearzoom2_chrome2

**Comment by ekelleyv** [comment]
I like the linear zoom a lot. However, I am having the double-zoom issue with apple trackpad as well. Also, it seems to break image overlays (I think it is the same issue @wboykinm pointed out). I am also on Chrome.

image

**Comment by mourner** [comment]
@wboykinm @ekelleyv thanks for the feedback! I think I know where the double-zoom comes from so I'll fix this. ImageOverlay seems like an unrelated regression though.

**Comment by amnesia7** [comment]
Would this help with the issue I've pointed out here https://github.com/Leaflet/Leaflet/issues/3178#issuecomment-72753838 with respect to events called when zooming (in my case I was using the scroll on touchpad) or have I already missed a fix for that that's already in master?

**Comment by danzel** [comment]
Seems awesome in Chrome on Windows.
IE11 on Windows does one zoom and then stops a moment and then does another.

This is me doing a big zoom out, then a bit zoom in:
zoom

**Comment by ChALkeR** [comment]
How could that solve #2757?
The problem in #2757 is that Leaflet reacts to both horizontal and vertical
zoom events, not only vertical, as it should.

2015-02-08 21:23 GMT+03:00 Dave Leaver <notifications@github.com>:

**Comment by mourner** [comment]
I now see that it's pretty much unusable on trackpad, so needs some more work...

**Comment by jonkoops** [comment]
@mourner Is this still something we'd want to introduce or can this PR be closed?

**Comment by mourner** [comment]
Let's close for now — not sure if we can reintroduce it in a buggy-free, compatible way.

**Pull request closed without merging**
