### PR TITLE
A few improvements in the Docs and on DivOverlay, Tooltip and Popup

### PR DESCRIPTION
**Pull request by Falke-Design**
**Improvements in the Docs: [Demo](http://falke-design.bplaced.net/leaflet/dist/#popup)**
- DivOverlay is now on the right place in the section `UI Layers`, before it was not added in the menu and placed at the bottom below `Events` [DivOverlay](https://leafletjs.com/reference-1.7.1.html#divoverlay)
- Popup and Tooltip references now to the functions of DivOverlay. Changed also the description Fixes: #6954, #6597
- Now it is possible to create anchor links from headers, when clicking on the link icon
- Anchor links they are in a collapsed accordion are now expanding the accordion if they are requested (tested in Firefox, Chrome, Edge, IE) [#divoverlay-bindpopup](http://falke-design.bplaced.net/leaflet/dist/#divoverlay-bindpopup)

**Added Features:**
- Fires on the popup self the events `popupopen` and `popupclose`
- DivOverlay (Popup & Tooltip) supports now  `content` in the options and as second parameter `latlng`. Very useful for standalone Popups or Tooltips, because the expected behaviour is to pass them on initializing.
Before:
```
var popup = L.popup()
    .setLatLng(latlng)
    .setContent('<p>Hello world!<br />This is a nice popup.</p>')
    .openOn(map);
```
Now:
```
var popup = L.popup({content: '<p>Hello world!<br />This is a nice popup.</p>'},latlng).addTo(map);
```

**Fixed Bugs:**
- Tooltip RTL support: was possible over css changes, explained [here](https://github.com/Leaflet/Leaflet/issues/7201#issuecomment-713112492). New function to the map is added `map.setRTLDirection(boolean)`, it adds the CSS-Class `leaflet-rtl` to the map container . During initialization the style `direction: rtl` is searched on the map container and if is found `setRTLDirection(true)` is called. Fix: #7201
- ~~If Tooltip is Sticky and Permanent it is now following mouse [comment in #7201](https://github.com/Leaflet/Leaflet/issues/7201#issuecomment-655746354)~~ PR: #7563 

**Additional thoughts:**
- DivOverlay has a default `offset: [0,7]` I think this would be better if this is moved to Popup and changed to [0,0] but this is a breaking change ...
- `.setTooltipContent("")` / `.setPopupContent("");` and  `.setContent("")` confuses developers, maybe this can explained better but I don't know how.

Restructured commits of PR: #7398

### CODE REVIEW

**Comment by johnd0e** [comment]
> I had big struggels to commit files in the correct line breaking format.

As I can see you haven't succeed in keeping newline style between commits.
So I am converting this to draft for now.

**Comment by Falke-Design** [comment]
@johnd0e and this means? What do you want from me to do?

**Comment by johnd0e** [comment]
> What do you want from me to do?

May be you will be able to fix wrong commits with interactive rebase.

**Comment by johnd0e** [comment]
> PS: I had big struggels to commit files in the correct line breaking format. It looks like some files are in `CRLF` and other files in `LF`

#995

**Comment by johnd0e** [comment]
@Falke-Design 
Perhaps c9c96eab9937adab67ae9ceff9fbe068b39e004c is here for mistake?

**Comment by Falke-Design** [comment]
@johnd0e No, this fixes: "If Tooltip is Sticky and Permanent it is now following mouse https://github.com/Leaflet/Leaflet/issues/7201#issuecomment-655746354"

**Comment by johnd0e** [comment]
I see, but still suggest to separate into different PR(s), leaving here Docs-related changes only.

**Comment by Falke-Design** [comment]
I will try next week to use interactive rebase and remove the not wanted changes. Should something else removed? Line-Break if it works and "If Tooltip is Sticky and Permanent it is now following mouse #7201 (comment)"

**Comment by Falke-Design** [comment]
@johnd0e I edited the Line Break commits and removed the tooltip bug "sticky & permanent" #7563

**Comment by Falke-Design** [comment]
@johnd0e yes I will do, this PR needs to be simplified

**Comment by Falke-Design** [comment]
Splitted into multiple PRs

**Pull request closed without merging**
