### PR TITLE
Added GeoRasterLayer Plugin

### PR DESCRIPTION
**Pull request by DanielJDufour**
First time adding a plugin to the site.  Let me know if I did something wrong or have any questions.  Thank you for your consideration :-)

### CODE REVIEW

**Comment by IvanSanchez** [comment]
If the plugin is meant to load GeoTIFFs, why is it **not** called GeoTIFFsomethingsomething? :thinking:

**Comment by DanielJDufour** [comment]
@IvanSanchez  , excellent question! The package used to be called geotiff-layer-for-leaflet (http://npmjs.com/package/geotiff-layer-for-leaflet).  However, we renamed it because we are in the process of adding NetCDF (CF Convention) support and also support for geo-referenced JPG and PNG files.  I felt it premature to mention these other file formats though because support for them is still in the works.  Open to your thoughts! =)

**Comment by jmbajo** [comment]
Excellent Plugin, I hope to see it anytime soon.

**Comment by Rennzie** [comment]
👍🏻 🚀

**Review by IvanSanchez — APPROVED** [review]

**Pull request merged**
