### PR TITLE
Possible fix for #4127, assume dblclick DOM event exists in touch-capable browsers

### PR DESCRIPTION
**Pull request by IvanSanchez**

### CODE REVIEW

**Comment by mourner** [comment]
The only issue with this is that it may make the performance problems on IE+touch even worse by adding even more event handlers to everything...

**Comment by IvanSanchez** [comment]
@mourner Skipping the native `dblclick` on modern IEs/edges should be easy enough, gimme a few minutes.

**Comment by IvanSanchez** [comment]
Interesting. I cannot reproduce #2820 anymore, so I guess skipping the native `dblclick` is not needed after all...

**Comment by kohenkatz** [comment]
Would it be possible to rebase this PR on top of the changes from #4143, to make testing easier?

**Comment by yohanboniface** [comment]
Not very comfortable with the workardound, but I've no plan B, it's and edge (haha) case, and we need to move on, so merging.

**Pull request merged**
