### PR TITLE
Fixes Layer.isPopupOpen when no popup is bound

### PR DESCRIPTION
**Pull request by gvangool**
This fixes uncaught exception when checking whether a popup isOpen(), when the layer has no popup bound to it.

### CODE REVIEW

**Comment by IvanSanchez** [comment]
Oooh, I like this. Could it be possible to add a unit test, which makes sure that a call to `isPopupOpen()` does not throw an error?

**Comment by gvangool** [comment]
Sure, but I wasn't able to find other unit tests for the `L.Layer` popup functions.

Do they exists?

**Comment by IvanSanchez** [comment]
No, maybe you should add them to https://github.com/Leaflet/Leaflet/blob/master/spec/suites/layer/PopupSpec.js . If you look at that file, you'll see it has tests for both `L.Popup` and the popup methods/options for `L.Map`. Having tests for the popup methods/options for `L.Layer` in the same place makes sense.

**Comment by gvangool** [comment]
Alright, I'll have a look tonight!

**Comment by gvangool** [comment]
@IvanSanchez this is my initial pass at the test cases, I kept 1 separate since I'm unsure whether this is actually expected behavior.

**Comment by IvanSanchez** [comment]
This looks quite good :+1: . One thing, though: As the current undesired behaviour is that a method call throws an error, the tests should explicitly check that the method call does indeed *not* throw an error (and check that, without your fix, the unit tests fail).

For reference, see https://github.com/Leaflet/Leaflet/blob/88d107ca969be9d7a5e7b17fafc4aadab466e18f/spec/suites/control/Control.LayersSpec.js#L104

**Comment by mepdr** [comment]
Tooltip has the same issue https://github.com/Leaflet/Leaflet/blob/master/src/layer/Tooltip.js#L371

**Comment by IvanSanchez** [comment]
@medpr Feel free to write a fix and some tests, then.

**Comment by gvangool** [comment]
@IvanSanchez changed the commits to first add the tests and only then change the behavior

**Comment by perliedman** [comment]
@gvangool could you rebase this on `master`? Other than that, I think we're good to merge

**Pull request merged**
