### PR TITLE
bringToFront / bringToBack for popups.

### LINKED ISSUE #3813: Cannot bring overlapped popups opened with Map#addLayer on top
When you have multiple popups opened with Map#addLayer and some of them overlapped with others, it is not possible to bring the one behind others front.
So we have part of popup A on top of popup B. It would be good when you click on B, it comes froward and popup A goes behind it.
Any thought?

### PR DESCRIPTION
**Pull request by danzel**
Will need a docs update too, will send over in a moment.

Fixes #3813

### CODE REVIEW

**Comment by yohanboniface** [comment]
And an entry in the CHANGELOG ;)

**Comment by danzel** [comment]
Sorted :+1:

**Comment by mourner** [comment]
@danzel this goes into beta2, not beta1 :)

**Comment by yohanboniface** [comment]
Well, my fault, my comment was not clear about beta2 being in a branch still :s

**Comment by danzel** [comment]
I'm bad at read :)

**Comment by danzel** [comment]
ok, that should do it!

**Pull request merged**
