### PR TITLE
Alternative fix for #3947

### PR DESCRIPTION
**Pull request by klaftertief**
This should not get merged when #3948 gets merged. See https://github.com/Leaflet/Leaflet/pull/3948#issuecomment-148707860

### CODE REVIEW

**Comment by klaftertief** [comment]
Just mentioning #3947 here in the comment again to have a reference in the issue itself.

**Comment by yohanboniface** [comment]
This seems a regression since 0.7.x, a `git bisect` would be helpful to be sure we are not breaking something else or missing the right fix, imho (idem for #3948).

**Comment by yohanboniface** [comment]
Bisecting point at 2191cfa8b035280215ab7dda0895e1abaa68e490 so I'm happy to leave it to @IvanSanchez :)

**Comment by klaftertief** [comment]
Thanks for the bisect. That was my guess in #3947 as well. '_animatingZoom' might get set too late to 'true' internally for a correct '_onZoomStart' behaviour.

**Comment by IvanSanchez** [comment]
Looks good to me :-)

**Pull request merged**
