### PR TITLE
Changed L.Marker to L.marker in all docs (reference-*.html)

### PR DESCRIPTION
**Pull request by billygarrison**

### CODE REVIEW

**Comment by cherniavskii** [comment]
@billygarrison but why?
Note, that `L.Marker` is a class, but `L.marker` is a factory.
See https://leafletjs.com/reference-1.4.0.html#class

**Comment by billygarrison** [comment]
Well that's unfortunate :sweat_smile:

Somewhere in the docs I was trying to follow an example that used `L.Marker` and it didn't work, so I switched it out with `L.marker` and it worked fine.

Perhaps it was [this example](https://leafletjs.com/reference-1.4.0.html#layer)?

Thanks for clearing up the difference between class and factory for me.

**Comment by cherniavskii** [comment]
@billygarrison yeah, you're right!

We generate docs from code comments, can you update this particular example?
Here's corresponding line:
https://github.com/Leaflet/Leaflet/blob/master/src/layer/Layer.js#L17

**Comment by billygarrison** [comment]
Done, thanks for your help!

**Pull request closed without merging**
