### PR TITLE
Rename 'closed' parameter of 'latLngsToCoords' to 'close' to avoid confusion

### PR DESCRIPTION
**Pull request by ronaldhoek**
I noticed the use of the parameter name `closed` in `latLngsToCoords` when looking at the changes or PR #7344.

But I got confused on what the usage is regarding this parameter as it suggests (because on the fact it's a noun) it states something about the current 'status' of the coords (`latlngs` parameter) being passed to the function.

Therefore I think it's better to change the name to `close`...

### CODE REVIEW

**Review by Falke-Design — CHANGES_REQUESTED** [review]
Please revert the changes of replacing tabs with spaces.

It is named `closed` because the argument needs to be true if the shape is `closed`.

**Comment by ronaldhoek** [comment]
> It is named closed because the argument needs to be true if the shape is closed.

But when I look at the function, with _shape_ you mean the `latlngs` parameter?
If so, when I look at the `closed` is interpreted, it actually closes (an action) the newly (based on the `latlngs`) created shape, so that the created shape is actually 'closed'.

So basically inside the function, a `close` action is performed on the shapedata to close it, creating a closed shape...

Therefore I suggest renaming the parameter from a 'noun' to a 'verb' as it gives a more clear understanding...

**Comment by ronaldhoek** [comment]
> Please revert the changes of replacing tabs with spaces.

Sorry about the spaces, used the wrong editor.

**Review by jonkoops — APPROVED** [review]
This seems fine to me, let's land this.

**Comment by ronaldhoek** [comment]
Thanks!

**Pull request merged**
