### PR TITLE
#6572 touch zoom events only to container instead of document

### PR DESCRIPTION
**Pull request by 7Ds7**

### CODE REVIEW

**Comment by 7Ds7** [comment]
This although disables the possibility of touch events on any other element than the map element itself

**Comment by johnd0e** [comment]
> although disables the possibility of touch events on any other element than the map element itself.

Do you mean that you still have some real issue with current code?

**Comment by johnd0e** [comment]
> we want map panning or pinch zooming to continue if one of the fingers went off the map.

Perhaps for most browsers we can use [setPointerCapture](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture) for that purpose.

**Comment by johnd0e** [comment]
Compare on and off:
https://github.com/Leaflet/Leaflet/blob/e213469a296ea00e6f9e6e6beb49d081e8d1c4fe/src/map/handler/Map.TouchZoom.js#L61-L62
https://github.com/Leaflet/Leaflet/blob/e213469a296ea00e6f9e6e6beb49d081e8d1c4fe/src/map/handler/Map.TouchZoom.js#L115-L116

I suspect that there 'off' misses a context:

```js
		DomEvent.off(document, 'touchmove', this._onTouchMove, this);
		DomEvent.off(document, 'touchend', this._onTouchEnd, this);
```

**Pull request closed without merging**
