### PR TITLE
Graceful degradation of zoom-pan animations, fixes #3272.

### LINKED ISSUE #3272: IE7-9 graceful degradation for animations & fractional zoom
In IE7-9, all API methods should never break. Fractional zoom levels should fallback to round ones. We can skip animations too.

### PR DESCRIPTION
**Pull request by IvanSanchez**

### CODE REVIEW

**Comment by mourner** [comment]
Great! Do you think that covers everything or any broken issues left? What IEs did you test?

**Comment by IvanSanchez** [comment]
I tested only IE8 in a VM, and IE11 on IE8 mode.

**Comment by mourner** [comment]
@IvanSanchez lets also make sure IE9 is good.

**Comment by IvanSanchez** [comment]
I just confirmed that the code at `debug/map/zoompan.html` works as expected in IE7, IE8 and IE9 :smile: 

Obviously there's still #2609, but that's a completely different issue, I guess.

**Comment by mourner** [comment]
:+1: awesome!

**Pull request merged**
