### PR TITLE
Create img badges directly in jekyll

### LINKED ISSUE #8716: Optimize star / recency labels on the plugins page
Follow up to #8714 — while it's a huge improvement, visiting the plugins page now invokes 1000+ network requests and makes the page very slow, in addition to a bunch of errors (around 60 for me). 

As a temporary workaround, we should add `loading="lazy"` to badge images, but long-term, ideally we would do away with badges and instead fetch / calculate stars and other metadata in a GitHub Action and then use it for rendering the static page. One of the advantages is instant page load, but another one would be that we can then extend the functionality of the page further, for example, adding dynamic sorting by stars or recency per category, highlight the most popular plugins, and style the rows differently depending on recency.

cc @Falke-Design @jonkoops

### PR DESCRIPTION
**Pull request by Falke-Design**
Attempt to create the badges directly in Jekyll.

Closes #8716, #8717

grafik

### CODE REVIEW

**Review by IvanSanchez — APPROVED** [review]
I cannot understand much Ruby (but the "piping data to a jekyll helper" bit looks good) , and my local installation of Jekyll is a bit of a mess, so I'm just gonna assume you've tested it.

**Review by mourner — APPROVED** [review]

**Comment by mourner** [comment]
@Falke-Design should probably be reverted — it's not working. The plugins page looks like this now:

image

**Comment by Falke-Design** [comment]
@mourner Done

**Comment by Falke-Design** [comment]
@mourner @jonkoops it is not possible to use custom filters with `github-pages` ... Github overwrites the directory path of the custom plugin with a random string, so it is never possible to include custom plugins / filters.

grafik
https://github.com/jekyll/jekyll/issues/5265#issuecomment-241267253

**Comment by jonkoops** [comment]
@Falke-Design any chance the fix mentioned in https://github.com/jekyll/jekyll/issues/5265#issuecomment-435327578 could also work for us here?

**Comment by Falke-Design** [comment]
@jonkoops no doesn't work 😕 

https://falke-design.github.io/Leaflet/plugins.html
https://github.com/Falke-Design/Leaflet/tree/docs/jekyll-badges
https://github.com/Falke-Design/Leaflet/blob/docs/jekyll-badges/docs/Gemfile

**Comment by jonkoops** [comment]
Ah that's a bummer indeed. It would be really nice if we could get it to work server-side.

**Comment by mourner** [comment]
@jonkoops in the meantime, maybe we could simulate the lazy loading by adding the badges when scrolling in view with `IntersectionObserver`?

**Comment by jonkoops** [comment]
I actually have a working version of the `loading="lazy"` functionality on my other machine. I'll see if I can pull it up once I have it up and running (moving countries atm).

**Pull request merged**
