### PR TITLE
Fix non-extendable objects regression of 1.1.0

### LINKED ISSUE #5650: in 1.1.0 all objects are non extendable
summing up #5643 and #5589, due to how the exports are done with the switch to rollup the leaflet objects are now all non extendable, so no plugin can add a new method to `L` or `L.Util`. 

Suggestions: republish 1.0.3 as 1.1.1 ASAP, this will prevent things from breaking, then either publish 1.1.0 as 2.0.0 or redo the switch to rolllup avoiding using `import * as foo from 'bar'` and `export * from 'foo'`;

### PR DESCRIPTION
**Pull request by mourner**
Closes #5650 until we figure out a less hacky solution. Tested it locally and it seems to work. I put the redefine in `Util` because it is currently included first in the Rollup build, but this is fragile. The advantage of this solution is that it changes just a few lines of code. cc @calvinmetcalf @perliedman  @IvanSanchez

### CODE REVIEW

**Comment by mourner** [comment]
Looks like this hack makes Phantom go crazy. Not sure how to fix the tests...

**Comment by mourner** [comment]
OK the tests seem to be running OK!

**Comment by jdalton** [comment]
This is breaking in an environment where `Object` methods are frozen and so they cannot be overwritten.

**Comment by jdalton** [comment]
Maybe wrapping it in a try-catch would help.

**Comment by jdalton** [comment]
PR created https://github.com/Leaflet/Leaflet/pull/6806

**Pull request merged**
