### PR TITLE
Create leaflet-markerplayer.md

### PR DESCRIPTION
**Pull request by 0n3byt3**

### CODE REVIEW

**Comment by 0n3byt3** [comment]
ok.. but is there a specific important reason for that?

**Comment by Falke-Design** [comment]
It will always reference back to `MovingMarker`, but you built a new plugin, so it should be a repo without a _fork_-reference.
Also it is a quality thing that a plugin in our list should not be a forked repo of a already existing plugin. 

grafik

**Comment by 0n3byt3** [comment]
thnx for your info and fast response... its done.. you can check it now

**Comment by 0n3byt3** [comment]
🤔👀

**Pull request merged**
