### PR TITLE
Vertical lines while moving over canvas elements

### PR DESCRIPTION
**Pull request by Ernie23**
Pull request for bug #5145

### CODE REVIEW

**Comment by IvanSanchez** [comment]
Tests are failing. @Ernie23, you might want to run `npm test` as explained in CONTRIBUTING.md

**Comment by Ernie23** [comment]
after some troubles, i've run npm test successfully ;)

**Comment by Ernie23** [comment]
@mourner I have taken your suggestion and committed the changes

**Comment by Ernie23** [comment]
So I should move these lines into the _draw function?

**Comment by perliedman** [comment]
@Ernie23 yes, also adding a check if the `_redrawBounds` is actually set before modifying them, of course.

**Comment by Ernie23** [comment]
@perliedman  I moved these lines into the  _redraw function. Is that okay?

**Comment by perliedman** [comment]
@Ernie23  :+1: Looks good!

**Comment by perliedman** [comment]
@Ernie23 just to double check, did you also verify that the fix still works as expected in the different cases you mentioned above?

**Comment by Ernie23** [comment]
@perliedman yes, I double checked this. These code changes in _redraw function still works.
I've tested this in following browser:
IE11/Edge - ok
Chrome (v54) - ok
Firefox (v51 beta) - ok
Safari (v. 10.0.1) - ok

So I think thats it 😉

**Comment by perliedman** [comment]
@Ernie23 Great work! Thanks a lot for a thorough bug report as well as a clean fix!

**Comment by Ernie23** [comment]
Your're welcome...
If in other cases help is needed, just contact me. 😉

**Comment by Ernie23** [comment]
@perliedman  can you close the issue?

**Comment by IvanSanchez** [comment]
If the PR has a comment like "fixes #bug-number", it will be closed automatically. It's a tiny neat trick :-)

**Comment by Ernie23** [comment]
@IvanSanchez okay... doesn't know that....😉

**Pull request merged**
