### PR TITLE
null ref after animation end

### PR DESCRIPTION
**Pull request by dnepromell**
If create map and remove it quickly a few place try to use removed mapPane

*Message:* "Cannot read property _leaflet_pos of undefined"

*Stack:* "TypeError: Cannot read property _leaflet_pos of undefined\n    at getPosition (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:2713:12)\n    at NewClass._getMapPanePos (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:4310:10)\n    at NewClass._moved (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:4314:18)\n    at NewClass.getCenter (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:3678:33)\n    at NewClass.<anonymous> (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:4455:17)\n    at NewClass.fire (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:588:11)\n    at NewClass._moveEnd (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:4100:15)\n    at NewClass.<anonymous> (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:4540:9)"

*Line:* 2713

*Message:* "Cannot read property _leaflet_pos of undefined"

*Stack:* "TypeError: Cannot read property _leaflet_pos of undefined\n    at getPosition (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:2713:12)\n    at NewClass._getMapPanePos (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:4310:10)\n    at NewClass._getNewPixelOrigin (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:4327:67)\n    at NewClass._move (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:4075:28)\n    at NewClass._onZoomTransitionEnd (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509738411:4536:8)"

*Line:* 2713

*Message:* "Cannot read property style of undefined"

*Stack:* "TypeError: Cannot read property style of undefined\n    at setTransform (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509739027:2682:5)\n    at NewClass.<anonymous> (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509739027:4457:4)\n    at NewClass.fire (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509739027:588:11)\n    at NewClass._moveEnd (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509739027:4100:15)\n    at NewClass.<anonymous> (http://localhost/js/app/vendor/leaflet-1.2.0.js?t=1509739027:4540:9)"

*Line:* 2682

### CODE REVIEW

**Comment by cherniavskii** [comment]
Also, could you provide minimal example reproducing this issue? It will help me to better understand the root of issue :)

**Comment by johnd0e** [comment]
> Also, could you provide minimal example reproducing this issue?

See #7116, #6115

**Comment by t1a2l** [comment]
@cherniavskii @johnd0e any news on this pull request? i added the changes to my local leaflet library and so far i cant reproduce the issue. Will let you know of any change.

**Comment by johnd0e** [comment]
- This PR lacks tests
- I do not like the approach itself: we should fix the cause of the issue, not consequences.

**Pull request closed without merging**
