### PR TITLE
Add new plugin - Leaflet.curve

### PR DESCRIPTION
**Pull request by elfalem**

### CODE REVIEW

**Comment by mourner** [comment]
Cool, thanks!

**Comment by jieter** [comment]
@elfalem note that your demo doesn't work for me.
You are loading het `leaflet.curve.js` file from raw.githubusercontent.com domain which sets MIME type `text/plain`:
2015-09-22-131002_705x653_scrot

You should add the script to the gh-pages branch and use a relative path.

**Comment by elfalem** [comment]
@jieter, thanks - that should be fixed now

**Comment by jieter** [comment]
Yes, works like charm now.

You can also ditch the master branch and use gh-pages as the main branch. This pattern is used by [some](https://github.com/mapbox/leaflet-image) [other](https://github.com/calvinmetcalf/leaflet-ajax) [plugins](https://github.com/jieter/Leaflet.layerscontrol-minimap), and makes sure your github pages is never out of sync.

**Comment by elfalem** [comment]
Thanks for the tip! I will try that.

**Pull request merged**
