### PR TITLE
Add L.DomEvent.once

### PR DESCRIPTION
**Pull request by yohanboniface**
@mourner not sure you'll merge this one ;)
But it's very useful, and also consistent with `L.Evented` API, so my opinion is that it's worth it. :)
Sadly I can't see a good way to factorize with `L.Evented.once`, but I see that none of `on` or `off` has been factorized.
Of course, I'll add a bit of doc if you think it's mergeable :)

### CODE REVIEW

**Comment by mourner** [comment]
Lets leave that out of core for now.

**Comment by yohanboniface** [comment]
Found today one more case where I needed it ;)  #lobbying ;)

**Comment by IvanSanchez** [comment]
> Found today one more case where I needed it ;) #lobbying ;)

+1 :-)

**Comment by yohanboniface** [comment]
One more use case today :) #lobbying

**Pull request closed without merging**
