### PR TITLE
Remove unnecessary gendered text in documentation

### PR DESCRIPTION
**Pull request by mvl22**

### CODE REVIEW

**Comment by IvanSanchez** [comment]
Plz read https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#improving-documentation carefully, and see https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L51

**Comment by danzel** [comment]
We do want this change @mvl22, you've just edited the wrong file.

**Comment by mvl22** [comment]
@danzel Thanks - in a busy few days at the moment so haven't had a moment to redo this. Happy for others to do so if they get a chance first.

**Comment by mvl22** [comment]
> Plz read https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#improving-documentation carefully

Thanks - now updated.

I had missed the second half of that section.

**Pull request merged**
