### PR TITLE
Add shadow-icon as svg icon and add white circle to marker-icon

### PR DESCRIPTION
**Pull request by Falke-Design**
Follow up #8766

This is my best result of creating the shadow as svg.
Maybe the `viewBox` needs to be changed but here ends my knowledge.

**Shadow icon diff:**
Left `.png`, right `.svg`:

grafik

grafik grafik

### CODE REVIEW

**Comment by jonkoops** [comment]
The SVG shadow seems a bit lighter, but it still looks nice. Perhaps we should we should also optimize these file with [`svgo`](https://github.com/svg/svgo) like we did in the past?

**Comment by Falke-Design** [comment]
> The SVG shadow seems a bit lighter, but it still looks nice. Perhaps we should we should also optimize these files with [`svgo`](https://github.com/svg/svgo) like we did in the past?

Yes it is a little bit lighter but was the best what I can achieve. 
SVGO sounds good but I would optimize it while generating the dist files and keep the source file like know.

**Comment by jonkoops** [comment]
> Yes, it is a little bit lighter but was the best what I can achieve. SVGO sounds good but I would optimize it while generating the dist files and keep the source file like know.

Fair enough, let's get this merged 👍

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
Thanks for the assist @Falke-Design 🙌

**Pull request merged**
