### PR TITLE
Added Leaflet.GeotagPhoto to list of plugins

### PR DESCRIPTION
**Pull request by bertspaan**
Added Leaflet.GeotagPhoto to list of plugins: 

- Demo: http://spacetime.nypl.org/Leaflet.GeotagPhoto/examples/camera.html
- Repo: https://github.com/nypl-spacetime/Leaflet.GeotagPhoto

### CODE REVIEW

**Comment by IvanSanchez** [comment]
The demo looks sweet! 👍 

I have one small complain, though. In Leaflet, class names are in `UpperCamelCase` while factory methods are in `lowerCamelCase`. This means that `L.TileLayer.WMS` is a class and `L.tileLayer.wms` is a factory. And, according to your docs, you have a `L.GeotagPhoto.crosshair` factory that should be in the `geotagPhoto` namespace instead, i.e. `L.geotagPhoto.crosshair`.

Not a showstopper, but I'd rather nitpick about the namespacing style :-)

**Comment by perliedman** [comment]
Wow, nice! I even have a use case that was just waiting for this plugin to be made! :smile:

**Comment by bertspaan** [comment]
@IvanSanchez: thanks for your comment, I will update the plugin!

@perliedman: good to hear! What are you going to use my plugin for?

**Comment by perliedman** [comment]
@bertspaan I have a side project where I render 3d scenes from OpenStreetMap data, and I have a Leaflet interface where you place the camera. I had a crude interface, but for example setting FOV was on my todo, and you already fixed all this, and it also looks nicer!

**Comment by bertspaan** [comment]
@perliedman Let me know if you publish anything online, I'd love to see it!

**Pull request merged**
