### PR TITLE
Simplify docs update process on release

### PR DESCRIPTION
**Pull request by mourner**
This PR simplifies the process of updating docs when releasing a new version to minimize the potential for mistakes, and get Leaflet closer to being able to do this automatically in GitHub Actions. Ref #7712 

- Remove redirect from `reference.html` to `reference-1.7.1.html`. Instead, `reference.html` contains docs for the latest stable release directly. Updates links accordingly.
- Make `npm run docs` update `dist/reference.html` directly instead of generating a temporary file that you have to manually move / edit. I guess that we might have had an intention to have self-contained offline docs in the `dist` some time in the past but it never actually happened it seems, and it's doesn't feel necessary in the modern age.
- Update `RELEASE.md`, removing all unnecessary steps.

### CODE REVIEW

**Review by Falke-Design — APPROVED** [review]
Looks good to me. But I don't know about it that well.

What if we create directly the reference-1.7.1.html and the reference.html? Then this step can never forget

**Comment by Falke-Design** [comment]
@mourner all current links are broke, because now it is `reference.html` and not https://leafletjs.com/reference-1.7.1.html anymore

**Comment by mourner** [comment]
@Falke-Design ah, we should bring it back but as a redirect this time so that old links aren't broken, right?

**Comment by Falke-Design** [comment]
Yes
My general suggestion would be that always the version reference (`reference-1.7.1.html`) is existing and the `reference.html`. If the newest version is `1.7.1` then `reference-1.7.1.html` redirects to `reference.html`. If then a new release is published  `reference-1.8.0.html` redirects to `reference.html` and `reference-1.7.1.html` is still existing. (Until all old release docs are removed)

**Comment by mourner** [comment]
Why would we do it for newer releases if there are no links to it yet? I think we can just limit this to 1.7.1

**Comment by Falke-Design** [comment]
Currently we provide the old docs too, until they are removed we should add the newest version to this list and keep it until all old docs are removed.

**Comment by Falke-Design** [comment]
@mourner FYI: https://leafletjs.com/reference-1.7.1.html is still missing

**Pull request merged**
