### PR TITLE
add QGIS2Leaf plugin

### PR DESCRIPTION
**Pull request by paulovieira**

### CODE REVIEW

**Comment by mourner** [comment]
Can you add it to a proper category?

**Comment by paulovieira** [comment]
The PR has been rebased. I created a new section under "3rd party integration" named "GIS integration". What do you think?

**Comment by mourner** [comment]
@paulovieira lets not create categories just for a single plugin. Moreover the 3rd party integration category is pretty short.

**Comment by IvanSanchez** [comment]
Somehow I feel it belongs to the "Overlay formats" (AKA vector formats) section.

**Comment by paulovieira** [comment]
Yes, the "Overlay data formats" is a better place for this plugin. The PR has been updated.

Great work with plugin organization @IvanSanchez!

**Pull request merged**
