### PR TITLE
Convert build scripts into ESM

### PR DESCRIPTION
**Pull request by jonkoops**
Converts the scripts in the `build` directory to use ECMAScript modules. This is part of a larger effort to convert all code in the project to ESM.

### CODE REVIEW

**Comment by jonkoops** [comment]
@Falke-Design do you have some time to look at these changes?

**Comment by Falke-Design** [comment]
sadly I have no experience with that, so I can't really say if this is ok or not

**Comment by jonkoops** [comment]
No worries. Just need someone to verify the scripts work as expected.

**Review by mourner — APPROVED** [review]

**Comment by jonkoops** [comment]
Thanks @mourner!

**Pull request merged**
