### PR TITLE
Fix the resource integrity hashes

### PR DESCRIPTION
**Pull request by jonkoops**
Also adds additional steps to the release process to prevent this from happening in the future.

### CODE REVIEW

**Comment by Falke-Design** [comment]
> adds additional steps to the release process

are missing 😄

**Comment by jonkoops** [comment]
> are missing :smile: 

No longer :+1:

**Review by Falke-Design — APPROVED** [review]

**Comment by jonkoops** [comment]
@mourner still seeing errors on https://leafletjs.com/, not sure why these resources do not match the hash.

**Comment by mourner** [comment]
@jonkoops I think I know — https://unpkg.com/leaflet@1.9.0/dist/leaflet.js has non-clean version in the header (should be just v1.9.0 but it also has a hash). Not sure why that happened, needs investigating. Meanwhile we can calculate the hashes for the files manually and update

**Comment by mourner** [comment]
I updated them manually, https://leafletjs.com/ is OK now.

**Pull request merged**
