### PR TITLE
Fix touch dblclick events (double tap) in recent Chrome versions

### PR DESCRIPTION
**Pull request by perliedman**
I finally took the time to dig into #5627 and its related issues (#5185, #5248 and probably a few more).

My summary is that in Chrome 55, the browser started firing `dblclick` events from touch (double taps), but this change was again reverted in some later version of Chrome, so recent Chromes _does not_ fire `dblclick` from touch.

Looking at the very handy matrix @IvanSanchez put together here https://github.com/w3c/pointerevents/issues/171, this leads me to believe IE is now _the only_ browser that fires `dblclick` from touch events.

This PR addresses this, and also tries to make it at least a little bit clearer what is going on in this code.

I've tested this in Chrome and Firefox on Linux, and it resolves the Chrome issue when device emulation is enabled; I will also try this out on IE and Edge. Testing this on more platforms would be very welcome.

### CODE REVIEW

**Comment by IvanSanchez** [comment]
The changes look good, but I'm slightly concerned about the market share for Chrome=v55 (and v56, and v57). Apparently v55 still ~0.35%, with v56 around ~0.15%. I don't know if it's worth it covering these edge cases or not.

**Comment by geoloep** [comment]
- Works with my laptop touch screen in Chrome and Firefox (Linux). 
- Works in Internet explorer 11 in normal mode and under windows phone emulation (Virtual Machine).
- Works in Edge in normal mode and under windows phone emulation (Virtual Machine)
- Work in Chrome on Android

**Comment by perliedman** [comment]
@IvanSanchez < 0.5% sounds really small to me, and by the time we manage to get out the next release, it will be even smaller 😜

**Comment by perliedman** [comment]
@geoloep thanks for trying those out! On my machine (Win10 laptop with a touch screen), IE11 and Edge both act equally weird with as well as without this fix, so I can't really make any conclusion from it...

**Comment by IvanSanchez** [comment]
@perliedman Well, we are supposed to care about IE8 and IE9 which have even smaller market shares... but it's your call 😄

**Comment by geoloep** [comment]
@perliedman I retried Edge and IE in native Windows 10, and the results are indeed a little strange
- IE 11: Double tap results in highlighting (selecting) the entire map pane. 1.2.0 works fine(!)
- Edge: Double tap works but (random?) markes and map tiles are also selected. This does not happen in 1.2.0 for me.

Chrome and Firefox work the same as in Linux. Regarding the microsoft browsers there seems to be a regression when compared to 1.2.0.

**Comment by perliedman** [comment]
@geoloep any chance you could try latest master? For me it looked like we had the same result in `master`. Guess we'll have to do a `git bisect` to find where this broke unless it's this PR that breaks it.

**Comment by geoloep** [comment]
Had to set up a build enviroment on windows first but have now managed to also try the latest master.

The results in Internet Explorer and Edge do not seem to be any different. IE is completely broken and Edge still selects random elements. I'm afraid the regression occured before this PR.

Even stranger: I notcied that the current master version works completely fine in Chrome! I tought that something might have changed in Chrome but my applications using Leaflet 1.2.0 are still broken and do not react to double taps. @perliedman perhaps you can confirm this?

**Comment by perliedman** [comment]
@geoloep for me, `master` was definitely broken in Chrome before this PR, when using device emulation mode i devtools - actually double tapping on my touch screen worked, though, which was really weird.

So did you test in Chrome with double taps on a laptop, or device emulated mouse clicks in devtools? No idea why that would make a difference, though...

**Comment by geoloep** [comment]
@perliedman I performed the test by double tapping on my touch screen laptop. I've just tried again in Linux and the results for Chrome are:

- Normal mode + Double finger tap works
- Devtools + Double finger tap works
- Devtools + Simulated double finger tap using mouse fails

This pull request does fix the last issue. Somewhere between 1.2.0 and the current master version the first two issues were also fixed it seems? I suppose it does not really matter in the end. I'll try to find some time in the coming week to try and figure out when and why IE and Edge broke.

**Comment by geoloep** [comment]
The first bad commit is 11cbfa809576c3c6e7f3bcb8631e6cf6fc06c685

**Comment by perliedman** [comment]
@geoloep thanks for doing the work to figure this out! Really appreciate the effort.

Now, how the hell can that change break this? :sob:

**Comment by geoloep** [comment]
@perliedman I've done some research and the line
```javascript
if (e.pointerType !== 'mouse' && e.MSPOINTER_TYPE_MOUSE && e.pointerType !== e.MSPOINTER_TYPE_MOUSE) {
```
Does not make sense to me. I'm thinking about the possible alternatives. It'll probably be better to create a new issue for this, seeing as it does not effect this pull request?

**Comment by perliedman** [comment]
@geoloep yep, a new issue is probably good.

Having said that, I think the intention is to check that `e.MSPOINTER_TYPE_MOUSE` is present (and not `undefined`), which I assume only happens in IE.

**Comment by fchabouis** [comment]
Hello,
I don't think this fix was part of the last release (v1.3.1).
Was it done on purpose ?
Thanks

**Comment by cherniavskii** [comment]
@fchabouis this PR is still open and obvious isn't part of latest release.
Comments above exmplain why ;)

**Comment by elf-pavlik** [comment]
FYI we currently use the branch from this PR in our webpack build since we do need that dblclick in Chrome. Also reading through all comments I haven't really understood what holds back merging it - I see one reviewer who approved it and no other reviewers who would request changes.

**Comment by fchabouis** [comment]
Yes, the discussion and current status was not clear to me. But upgrading from a v1.2.0 to a v1.3.1 made the dblClick work on my android chrome. So I'm still confused about it, but well, it's working so I'm fine with it.

**Comment by jjimenezshaw** [comment]
Hi!
Thanks @perliedman . I am happy to see that this PR is aligned with the changes I proposed on #5627.
However, I am really confused now. 

- Leaflet 1.3.1 is released (without this PR)
- My Android 7.1.1 with Chrome 63.0.3239.84 works well in the page http://leafletjs.com (the map from London). :grinning: (I mean, double tap makes zoom properly)
- Nevertheless it doesn't work on this example (from a simple plugin of mine), also with Leaflet 1.3.1 https://jjimenezshaw.github.io/Leaflet.UTM/examples/input.html :confused:

What is happening here?

**Comment by perliedman** [comment]
@jjimenezshaw sorry to say I don't really know. I failed to follow up on this PR after the issues reported by @geoloep, so I'm not really sure about the current state. Given that `dblclick` started to work again for some configurations, I guess Chrome changed something (again), but I have no details.

**Comment by geoloep** [comment]
It's true that double tap to zoom seems to work again in 1.3.1. 1.2.0 is still broken so I don't think a change in browser behavior is the cause.

In my applications the return of double tapping cause some troubles because click events are fired. Double tapping to zoom therefore also results in selecting items on the map. Is that the intended behavior? If dbclick events cannot be distinguished from click events they are still broken from the point of view of my use cases.

**Comment by jjimenezshaw** [comment]
I found the difference between leafletjs.com and my example:
After adding `<meta name="viewport" content="width=device-width" />` to my example, it reacts to double tap in Chrome (with leaflet 1.3.1, but not 1.2.0)

On the other side, doing `git bisect`, I found that the double tap works since commit
11cbfa809576c3c6e7f3bcb8631e6cf6fc06c685

**Comment by geoloep** [comment]
@jjimenezshaw That makes sense since it reverts the first bad commit that I discovered.

**Comment by perliedman** [comment]
@geoloep just do understand... in https://github.com/Leaflet/Leaflet/pull/5881#issuecomment-341385181, you said 11cbfa8 is the first _bad_ commit, but now it sounds like it's actually the fix?

If it is indeed the fix, it would make a lot more sense, I was perplexed that 11cbfa8 would introduce more problems.

**Comment by geoloep** [comment]
@perliedman I've seemed to have made a mistake in my reasoning there. I should have re-read the discussion better again. In https://github.com/Leaflet/Leaflet/pull/5881#issuecomment-340267472 I already noticed that double tap to zoom already worked in Chrome again and that change occurred somewhere between 1.20 and then. @jjimenezshaw is right that https://github.com/Leaflet/Leaflet/commit/11cbfa809576c3c6e7f3bcb8631e6cf6fc06c685 is the cause of this.

https://github.com/Leaflet/Leaflet/commit/11cbfa809576c3c6e7f3bcb8631e6cf6fc06c685 is also the first commit wherein the issues in IE & Edge that are mentioned above started to occur. (According the bisect that I performed then). So we're confusing 2 different issues here that occur in different browsers (Chrome vs Edge & IE).

I'm sorry for adding to the confusion. I'll try to do some test runs of 1.3.1 in the Microsoft browsers.

**Comment by jjimenezshaw** [comment]
Here are my 2 cents: The test environment that was in the playground, to log the mouse events, now in plnkr:
https://plnkr.co/edit/RUoykCaIhwpAxLgD9xgM?p=preview

**Comment by geoloep** [comment]
I can still select/highlight map tiles in Internet Explorer and Edge by double tapping the touch screen on the leafletjs.com homepage and using the debug maps from the repository.

In Plunker the highlighting does not happen but the map eventually bugs out. I'm not sure leaflet is to blame or the plunker environment. I experience things like the map not wanting to pan any-more, or one finger swipes resulting in zooming in stead of panning. I would not pick up on this unless someone else can reproduce this.

I'm just relating my experiences in the hope that they will be useful!

**Comment by cherniavskii** [comment]
@geoloep Plunker may embed your example in iframe, which may cause that difference. Try Preview mode in separate window - this may help

**Comment by geoloep** [comment]
With the preview mode in a separate app the plunkr test environment works fine, I could not select tiles by double tapping like I can on the leafletjs.com homepage.

**Pull request closed without merging**
