### PR TITLE
Better Icon.Default imagePath detection using regex

### PR DESCRIPTION
**Pull request by oleg-andreyev**
Regex covers:
- url(http://localhost:8000/base/dist/images/marker-icon.png)
- url(http://localhost:8000/base/dist/images/marker-icon-2x.png)
- url(http://localhost:8000/base/dist/images/marker-icon.hash.png)
- url(http://localhost:8000/base/dist/images/marker-icon-2x.hash.png)
- url("http://localhost:8000/base/dist/images/marker-icon.png")
- url('http://localhost:8000/base/dist/images/marker-icon.png')

### CODE REVIEW

**Comment by oleg-andreyev** [comment]
@IvanSanchez I'm okay with helping other developers.

**Comment by johnd0e** [comment]
Test is failing:
```
PhantomJS 2.1.1 (Windows 8.0.0) Marker.Drag drag in CSS scaled container drags a marker with mouse, compensating for CSS scale FAILED
        Error: expected 0 to be within -50..-30 (node_modules/expect.js/index.js:102)
```

**Comment by johnd0e** [comment]
Ok, there is a bug in tests. I've found how to fix it.

**Comment by oleg-andreyev** [comment]
@johnd0e thanks! I haven't looked into it, because I'm not sure if it's related to this PR.

**Pull request closed without merging**
