### PR TITLE
Add `playsInline` attribute on the video element

### LINKED ISSUE #7357: Video overlay: `playsinline` attribute required for phones on iOS
https://webkit.org/blog/6784/new-video-policies-for-ios/:

> - On iPhone, `<video playsinline>` elements will now be allowed to play inline, and will not automatically enter fullscreen mode when playback begins.
> `<video>` elements without `playsinline` attributes will continue to require fullscreen mode for playback on iPhone.

Might we worth to add the attribute by default. See the HTML [`playsinline` attribute](https://html.spec.whatwg.org/multipage/media.html#attr-video-playsinline) definition.

### PR DESCRIPTION
**Pull request by donnisnoni**
Fixes #7357

### CODE REVIEW

**Comment by IvanSanchez** [comment]
Just checking - has this been tested on an actual iOS device?

**Comment by donnisnoni** [comment]
Not yet... but maybe @Malvoz can help to test it...

**Comment by Malvoz** [comment]
@donnisnoni I don't own an iOS device (I just made the observation and reported on the potential requirement), sorry.

**Comment by IvanSanchez** [comment]
Well, even though the code looks good (thanks @donnisnoni for sending the PR), I'd rather not merge until it has been tested (and I don't have a iOS device either)

**Pull request closed without merging**
