### PR TITLE
Add missing hasOwnProperty check

### PR DESCRIPTION
**Pull request by infostreams**
Without this I got a very cryptic "Cannot read property '_leaflet_id' of undefined" error. This fixes it.

### CODE REVIEW

**Comment by nathancahill** [comment]
-1. `this._layers` is an array, so the error you're seeing must be coming from somewhere else (in `this._addItem` maybe?) Can you create an minimal example that reproduces the issue? https://playground-leaflet.rhcloud.com/

**Comment by IvanSanchez** [comment]
@infostreams Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this bug?

**Comment by infostreams** [comment]
Basically I did this:

    L.control.layers(null, {
        key_a:new L.TileLayer("url"), 
        key_b:new L.TileLayer("url")
    }, {position: "bottomleft"}).addTo(map);

I can't get your playground to work (I tried, but the default thing it opens is showing javascript errors for me), but this is what triggered the `Cannot read property '_leaflet_id' of undefined` error for me.

If you assume that people are only going to pass in arrays into that function, then I think the original code works. Otherwise we have to add something more involved than what I just proposed

**Comment by infostreams** [comment]
Huh? Wait, my version of leaflet-src.js says `for (i in this._layers) {` just above the `if (this._layers.hasOwnProperty(i)) {` I added, but the version I made the pull request for says `for (i = 0; i < this._layers.length; i++) {`....

**Comment by infostreams** [comment]
Related thread: https://github.com/Leaflet/Leaflet/issues/4508. Uhm, close? I guess?

**Comment by nathancahill** [comment]
Yep, looks like it's fixed in current master then. Thanks!

**Pull request closed without merging**
