### PR TITLE
Fix indentation issues in Karma config

### PR DESCRIPTION
**Pull request by jonkoops**
Removes mixed spaces used for indentation in the Karma config file.

### CODE REVIEW

**Comment by Falke-Design** [comment]
Can this checked over eslint?

**Review by Falke-Design — APPROVED** [review]

**Comment by jonkoops** [comment]
> Can this checked over eslint?

Yes, we can lint the entire `spec` directory, but that will throw errors due to usage of Node APIs such as `process`.

**Review by johnd0e — APPROVED** [review]

**Comment by Falke-Design** [comment]
> to usage of Node APIs such as process.

Would it possible to add `// eslint-disable-next-lin` ?

**Comment by mourner** [comment]
You can do a file-wide specific rules override in a eslint comment at the top of `karma.conf.js`. Let's follow-up in a different PR.

**Pull request merged**
