### PR TITLE
Allow subscribing to standalone popup events

### PR DESCRIPTION
**Pull request by lightoze**

### CODE REVIEW

**Comment by mourner** [comment]
Can you describe the rationale behind this? What's the use case?

**Comment by lightoze** [comment]
I am creating a standalone (i.e. not attached to a marker) popup layer and I need to know when it's closed.

**Comment by IvanSanchez** [comment]
@lightoze There are already events fired from the popup https://mourner.github.io/Leaflet/reference.html#popup-removed

**Comment by lightoze** [comment]
My bad, I was consulting 0.7 documentation at http://leafletjs.com/ and it's not mentioned there.
Also https://mourner.github.io/Leaflet/reference.html#popup-removed says that event name is `removed`, but it is in fact `remove`. Thank you for pointing out where to look at, anyway.

**Pull request closed without merging**
