### PR TITLE
fixing typo lon->lng in refence.html file

### PR DESCRIPTION
**Pull request by shashwat010**
Fixes: #8461

### CODE REVIEW

**Review by Falke-Design — CHANGES_REQUESTED** [review]
You need to change the line in the code:
https://github.com/Leaflet/Leaflet/blob/b0acb6114f13b96f559c72530d18c98e73e88c82/src/geo/LatLng.js#L20

And let us remove the line completley

**Comment by shashwat010** [comment]
should i remove line 20 aur fix typo?

**Comment by Falke-Design** [comment]
Please remove it

**Comment by shashwat010** [comment]
Please review it.

**Review by Falke-Design — APPROVED** [review]
Thx

**Pull request merged**
