### PR TITLE
Use Pointer Events for `Map.BoxZoom`

### PR DESCRIPTION
**Pull request by jonkoops**
Works towards closing #7200

### CODE REVIEW

**Review by IvanSanchez — APPROVED** [review]
LGTM.

Now I want to test this with something that has both a touchscreen (for the finger) and a keyboard (for the `shift` key)

**Review by Falke-Design — CHANGES_REQUESTED** [review]
What is with `mousemove` and `mouseup` in Line 75 & 113?

**Comment by Falke-Design** [comment]
Here a short test for each type:
```
	it('create zoom box mouse', (done)=>{
		expect(map.getZoom()).to.eql(3);

		// fire mousedown event with shiftKey = true, to start drawing the boxZoom
		let clientX = 100;
		let clientY = 100;
		let event = new CustomEvent('mousedown');
		event.shiftKey = true;
		event.clientX = clientX;
		event.clientY = clientY;
		event.button = 1;
		map._container.dispatchEvent(event);

		// fire mousemove event with shiftKey = true, to draw the boxZoom
		clientX += 100;
		clientY += 100;
		event = new CustomEvent('mousemove');
		event.shiftKey = true;
		event.clientX = clientX;
		event.clientY = clientY;
		event.button = 1;
		document.dispatchEvent(event);



		event = new CustomEvent('mouseup');
		event.shiftKey = true;
		event.clientX = clientX;
		event.clientY = clientY;
		event.button = 1;
		document.dispatchEvent(event);

		setTimeout(()=>{
			expect(map.getZoom()).to.eql(5);
			done();
		},1000)
	});

	it('create zoom box touch', (done)=>{
		expect(map.getZoom()).to.eql(3);

		// fire mousedown event with shiftKey = true, to start drawing the boxZoom
		let clientX = 100;
		let clientY = 100;
		let event = new CustomEvent('touchstart');
		event.shiftKey = true;
		event.clientX = clientX;
		event.clientY = clientY;
		event.button = 1;
		map._container.dispatchEvent(event);

		// fire mousemove event with shiftKey = true, to draw the boxZoom
		clientX += 100;
		clientY += 100;
		event = new CustomEvent('touchmove');
		event.shiftKey = true;
		event.clientX = clientX;
		event.clientY = clientY;
		event.button = 1;
		document.dispatchEvent(event);



		event = new CustomEvent('touchend');
		event.shiftKey = true;
		event.clientX = clientX;
		event.clientY = clientY;
		event.button = 1;
		document.dispatchEvent(event);

		setTimeout(()=>{
			expect(map.getZoom()).to.eql(5);
			done();
		},1000)
	});

	it('create zoom box pointer', (done)=>{
		expect(map.getZoom()).to.eql(3);

		// fire mousedown event with shiftKey = true, to start drawing the boxZoom
		let clientX = 100;
		let clientY = 100;
		let event = new CustomEvent('pointerdown');
		event.shiftKey = true;
		event.clientX = clientX;
		event.clientY = clientY;
		event.button = 1;
		map._container.dispatchEvent(event);

		// fire mousemove event with shiftKey = true, to draw the boxZoom
		clientX += 100;
		clientY += 100;
		event = new CustomEvent('pointermove');
		event.shiftKey = true;
		event.clientX = clientX;
		event.clientY = clientY;
		event.button = 1;
		document.dispatchEvent(event);

		event = new CustomEvent('pointerup');
		event.shiftKey = true;
		event.clientX = clientX;
		event.clientY = clientY;
		event.button = 1;
		document.dispatchEvent(event);

		setTimeout(()=>{
			expect(map.getZoom()).to.eql(5);
			done();
		},1000)
	});
```

**Comment by jonkoops** [comment]
> What is with `mousemove` and `mouseup` in Line 75 & 113?

Good catch, we should be changing those as well.

**Review by IvanSanchez — APPROVED** [review]
LGTM

**Review by Falke-Design — APPROVED** [review]
I think we should add more tests, but they can be added in a different PR

**Comment by jonkoops** [comment]
Fixed the merge conflicts, I'm going ahead and merge this in.

> I think we should add more tests, but they can be added in a different PR

Do you feel like picking this up @Falke-Design? Can also log an issue, so we can pick it up later.

**Pull request merged**
