### PR TITLE
update reference for layerGroup methods

### PR DESCRIPTION
**Pull request by loorinm**
Added documentation for an additional use for these methods which was not listed.

### CODE REVIEW

**Comment by mourner** [comment]
Hmm, I'm not sure — does it really do that? `group.addLayer(layer)` only adds a layer to the group. It only adds that layer to the map if the group was added to the map before.

**Comment by loorinm** [comment]
I'm using this code to repeatedly add and remove layerGroups from the map:

    //adjust the markers on the page accordingly
    if (tone.status) {
      //show all the layers in the group
      $scope.map.addLayer($scope.layerGroups[tone.name])
    } else {
      //hide all the layers in the group
      $scope.map.removeLayer($scope.layerGroups[tone.name])
    }

here's my app:
tweetmoodmap.herokuapp.com

**Comment by hyperknot** [comment]
@loorinm I think you are mistaking `map.addLayer` with `layerGroup.addLayer`. They are both called the same, but their documentation is in different part of the page.

Look:
http://leafletjs.com/reference.html#map-addlayer
and
http://leafletjs.com/reference.html#layergroup-addlayer

**Comment by loorinm** [comment]
Ahh, I see now. Thanks for the clarification!

**Pull request closed without merging**
