### PR TITLE
Import Leaflet in tests using JavaScript modules

### PR DESCRIPTION
**Pull request by jonkoops**
Changes the unit tests so they use the named exports from Leaflet loaded trough an import map.

### CODE REVIEW

**Comment by jonkoops** [comment]
Interesting, tests sometimes fail. I have no idea why yet, will look at it another time (gotta sleep).

**Comment by mourner** [comment]
> Interesting, tests sometimes fail. I have no idea why yet, will look at it another time (gotta sleep).

Looks like all the failures are timeouts — I guess browsers take to long to hop through all the imports and fetch everything.

Also noting that the total test time jumps from <3m to 6–8m. We should look into addressing that before shipping — perhaps this alone would be enough to keep running against the bundle. It may also be beneficial because some issues may only manifest after bundling, which is how users end up using the code anyway, so tests closer to real world.

**Comment by jonkoops** [comment]
> Perhaps this alone would be enough to keep running against the bundle.

How do you mean? We are currently still running the tests against the bundled code. Or are you referring to #8937?

I am not quite sure what is causing the performance to regress so much, I'll have to take a look and investigate deeper.

**Comment by mourner** [comment]
@jonkoops ah right, I missed that it's not yet implementing individual file import. But the regression is indeed suspicious — let's make sure it's not slower before we can land this.

**Comment by jonkoops** [comment]
I'm closing this PR so that I can merge this work into a larger effort to start using [Web Test Runner](https://modern-web.dev/docs/test-runner/overview/). See #8939 for more information.

**Pull request closed without merging**
