### PR TITLE
add leaflet-mapkey-icon plugin

### PR DESCRIPTION
**Pull request by filipzava**

### CODE REVIEW

**Comment by yohanboniface** [comment]
Needs rebase. Maybe one commit for the three plugins would have been a good idea ;)

**Comment by filipzava** [comment]
Yes, one commit. That's clear. It was my first pull request and I was eager :). So it needs rebase? This is my part or should I do new commit? Thx

**Comment by yohanboniface** [comment]
> So it needs rebase? This is my part or should I do new commit? Thx

Yes, up to you :)
Basically, all your PRs changes the same place of the file, so as soon as one is merged, the others are conflicting. So you need to rebase upon an up to date gh-pages branch, this will conflict, you then need to fix the conflict by hand, git add and continue rebase.
Doing a new PR may be a simpler way, but North faces are the best school ever, no? ;)

**Comment by filipzava** [comment]
OK, thank you very much for your advice :)

**Pull request closed without merging**
