### PR TITLE
#9059 Fix - Removed convoluted map-moving / tooltip showing logic

### PR DESCRIPTION
**Pull request by dscarb21**
Code was deemed to be unecessary and leads to multiple tooltips showing up at once. Removing allows for clean functionality. 

Fixes: #9059

### CODE REVIEW

**Comment by IvanSanchez** [comment]
You say «leads to multiple tooltips showing up at once». Under what circumstances does this happen?

**Review by Falke-Design — CHANGES_REQUESTED** [review]
We should not remove this without having a solution for #8672, which was the purpose for this code

**Comment by Falke-Design** [comment]
> You say «leads to multiple tooltips showing up at once». Under what circumstances does this happen?

@IvanSanchez I think this should fix #9059

tooltip_sticks

**Comment by dscarb21** [comment]
Apolgies, didn't fully understand functionality of #8672 fix. Changed the flag that is used to "schedule" tooltip opening to a property on the map object rather than the tooltip itself. This fixes all of those tooltips displayed at once, demonstrated by @Falke-Design. Set this flag to "true" in closetooltip which gets rid of a small bug where it opens the tooltip even when the cursor has left the marker.

**Comment by jonkoops** [comment]
Superseded by https://github.com/Leaflet/Leaflet/pull/9154

**Pull request closed without merging**
