### PR TITLE
Port #4173 to master: dashArray in Canvas

### PR DESCRIPTION
**Pull request by IvanSanchez**
Allows using `dashArray` in `<canvas>` renderers.

### CODE REVIEW

**Comment by yohanboniface** [comment]
Worth a unittest?

**Comment by IvanSanchez** [comment]
@yohanboniface This is a graphical thing - in order to do unit tests for this we would need to do like Mapnik does, and compare screenshots to reference screenshots. Bit of an undertaking right now?

**Comment by yohanboniface** [comment]
Was just thinking about testing that the attributes are on the DOM element. But maybe that would be like testing browser Canvas implementation at the end…

**Comment by mourner** [comment]
Oh, I didn't even notice it was for stable previously...

**Comment by gommo** [comment]
We just found out that setLineDash isn't supported on IE10 and below so the code needs to check for that

**Comment by IvanSanchez** [comment]
@gommo Is there any workaround for IE10? According to https://msdn.microsoft.com/en-us/library/dn265063%28v=vs.85%29.aspx , it doesn't seem like it.

We might just need to note this down in the API docs for the `dashArray` option.

**Comment by gommo** [comment]
I'll need to add a change so we don't actually call setLineDash

**Comment by IvanSanchez** [comment]
@gommo Wait - does IE10 throw an error or something like that?

**Comment by gommo** [comment]
Yeah it does!

**Comment by IvanSanchez** [comment]
@gommo Then we need to fix this again!

**Pull request merged**
