### PR TITLE
Switch to wheel event where available

### LINKED ISSUE #2757: Jumpy scrolling with touchpad (vertical/horizontal double finger scroll).
When using a touchpad with double-finger scroll enabled for both vertical and horizontal directions, the scroll becomes jumpy in some cases.

This happens when the user moves his fingers not following a straight vertical line, but a bit in horizontal direction. For example, left and bottom cause opposite scrolling, so left-bottom movement becomes jumpy.

This could be solved simply by ignoring horizontal mouse scroll events (like google maps do).

### PR DESCRIPTION
**Pull request by mourner**
May fix #2757 #2732. We don't care about FF17 and less where `MozMousePixelScroll` was needed anymore.

### CODE REVIEW

**Comment by IvanSanchez** [comment]
Now looks good on FFX 38 (which scrolls by lines) and Chromium 46 (which scrolls by pixels) on both a trackpad and a mouse.

Need to check:
- [ ] IE8 
- [ ] IE 10/11 w/ mouse
- [ ] IE 10/11 w/ trackpad
- [ ] Safari w/ mouse
- [ ] Safari w/ magic mouse, trackpad

**Comment by mourner** [comment]
That's cool, although delta in IE that was `/ 40` is now `/ 2`, which looks kinda weird. Did we make it 20 times more sensitive?

**Comment by IvanSanchez** [comment]
@mourner Now we normalize into pixels instead of into lines. In order to get a smooth result in Firefox with default settings, 3 lines has to be mapped to (at least) 52 pixels.

The legacy IE deltas are always 120 pixels. It seems logical to convert them into 60 pixels now (instead of 3 lines), although it needs testing.

**Comment by IvanSanchez** [comment]
> Now we normalize into pixels instead of into lines.

We should mention this in the 1.0.0 docs, BTW.

**Comment by mourner** [comment]
This looks pretty good now, should we merge now and track any concerns in new issues? Do we need any more testing before merge?

**Comment by IvanSanchez** [comment]
I've tried with as many devices I could (which is quite a few), so yeah.

**Comment by mourner** [comment]
:+1: awesome!

**Pull request merged**
