### PR TITLE
Reimplement DoubleTap simulation in more simple and reliable way

### LINKED ISSUE #7106: Double tap breaks zoom out on iOS
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Open https://leafletjs.com/
- Double tap on map
- Continuously tap on zoom out control

**Expected behavior**
Pressing on zoom out should zoom out

**Current behavior**
In the GIF below I'm double tapping on the map to zoom in and then pressing on the zoom out control multiple times. Notice how the zoom level changes unexpectedly. It starts by zooming in, then at some point switches to zooming out and again to zooming in.

ezgif-2-f76aa56882eb

**Environment**
- Leaflet version: 1.5.1, 1.6.0 and whatever is used on https://leafletjs.com/
- Browser (with version): Safari
- OS/Platform (with version): iOS 13.4.1

### LINKED ISSUE #7419: Leaflet 1.7.1 + Ionic React / Capacitor: no double click on generated iOS app
Hello

I am using Ionic React / Capacitor with Leaflet 1.7.1 to build iOS and Android apps, but the double click is not working on the generated iOS app.
The map does not zoom in and the `dblclick` events are not triggered.

Here is the Browser object in iOS:
**"ie":false,
"ielt9":false,
"edge":false,
"webkit":true,
"android":false,
"android23":false,
"androidStock":false,
"opera":false,
"chrome":false,
"gecko":false,
"safari":false,
"phantom":false,
"opera12":false,
"win":false,
"ie3d":false,
"webkit3d":true,
"gecko3d":false,
"any3d":true,
"mobile":true,
"mobileWebkit":true,
"mobileWebkit3d":true,
"msPointer":false,
"pointer":true,
"touch":true,
"mobileOpera":false,
"mobileGecko":false,
"retina":true,
"passiveEvents":true,
"canvas":true,
"svg":true,
"vml":false}**

and the navigator.userAgent:
**Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148**

I looked at the code and the function `browserFiresNativeDblClick` (in DomEvent.js) returns true, indicating a native double click support.
But it doesn't work as expected. Do you have any idea?

Just for testing, I locally and temporary changed browserFiresNativeDblClick to always return false and it starts working successfully on the iOS device.

I also precise it is working fine in the generated Android app.

Thanks.

### LINKED ISSUE #7422: disableClickPropagation fails after double tapping map on iOS
IMG_2DE51D162B81-1

**Steps to reproduce**
- Open [https://6v1ht.csb.app](https://6v1ht.csb.app) on iOS device
- **Double tap** on upper 50% of map to zoom
- **Single tap** on overlay element  in lower 50% of map

**Expected behavior**
- **Single tap** on overlay element should not do anything because it is a `<div>` with `disableClickPropagation`

**Current behavior**
- Map zooms in

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): iOS Safari
- OS/Platform (with version): iOS 14.3

**Additional context**
- Also broken on [https://shademap.app](https://shademap.app) when you attempt to use slider at bottom of map.
- Thank you for maintaining this amazing library. I am investigating the bug and hoping to narrow down the cause. Any guidance is greatly appreciated.

**Minimal example reproducing the issue**
https://codesandbox.io/s/epic-stonebraker-6v1ht?file=/src/index.js

### PR DESCRIPTION
**Pull request by johnd0e**
Take advantage of observations from #7012:

Base handler on 'click' event instead of 'touch*' / 'pointer*'.
Ensure that simulated 'dblclick's are fired only when needed.

ATM it's safe to use in any known browser, with or without touch support,
and it is equally efficient with or without pointer events.

Additionally: reduce `delay` value to 200, as it is closer to actually observed.

Fix #7106, fix #7419, fix #7422.
Also new approach can easily fix issues like #6777.

---
Test page: https://gist.githack.com/johnd0e/12cb0d6c2aead30ea7f2e17c5f9991be/raw/test-doubletap.html

### CODE REVIEW

**Comment by johnd0e** [comment]
Well, I'm not quite sure about last commit.

As we can see (https://github.com/Leaflet/Leaflet/issues/7012#issuecomment-595087386), there are 2 known cases when `dblclick` is not produced on double-tapping in modern browsers.
But it's not clear if those cases are ever valid.

What if it's more like browsers bugs, that should be fixed in their respective sources?

**Comment by johnd0e** [comment]
I believe that this PR is ready to be merged.

Possible future enhancements:
- Some way to disable simulation, like [global switch](https://leafletjs.com/reference-1.7.1.html#global-switches), or `L.Browser` property (after #7335).
- Add some tests.

**Comment by johnd0e** [comment]
Tests added: f9a7edceee49c96ec215c23f187bfb17d068c2e3

**Review by Falke-Design — APPROVED** [review]
Nice refactoring!

**Review by mourner — APPROVED** [review]

**Pull request merged**
