### PR TITLE
Add an option to L.Path to allow the user to set the clicktolerance of a single layer

### PR DESCRIPTION
**Pull request by geoloep**
This is a suggestion for a new path option. It will only affect Canvas layers.

On non-touch browsers the clickTolerance is set to the weight of the stroke. In my real world projects the weight of polylines is way to small to create a usable clickable area. Current available options to alleviate this issue is to increase the weight or draw a second invisible polyline with increased weight. Both have their drawbacks.

It would be convenient to set a buffer area around the polyline that is also clickable. Since the _clickTolerance function is already present the only required change is to allow the user to influence the result of this function. By adding this as an path option, only specific layers will be affected.

I haven't contributed code to a project such as Leaflet before, the additions are mainly to show what I had in mind. I hope it is clear. I can expand on this request if necessary.

[Demo](http://demo.geoloep.nl/clickTolerance/)

### CODE REVIEW

**Comment by IvanSanchez** [comment]
> I haven't contributed code to a project such as Leaflet before, the additions are mainly to show what I had in mind.

The code and the PR is actually good, don't worry about that :-D

> By adding this as an path option, only specific layers will be affected.

I'm not fully sure this is the best way? In my head, it would be a bit cleaner to set a `clickTolerance` option in the `L.Canvas` renderer, e.g.

```
return (this.options.stroke ? this.options.weight / 2 : 0) + (touch ? this._renderer.options.clickTolerance || 0 : 0);
```

> By adding this as an path option, only specific layers will be affected.

What's your use case for a per-layer click tolerance?

**Comment by geoloep** [comment]
> What's your use case for a per-layer click tolerance?

I can imagine the additional clicktolerance would be annoying on polygons. Especially when multiple polygons touch each other. I came across this relevant issue: #5144. Closely clustered circleMarkers would give the same problem. There isn't really a use case on layers other than polylines I suspect.

I myself would only need added tolerance on certain polylines, and then the required tolerance might also depend on the weight of the line and perhaps the zoom level where I expect interaction to occur. I'm a developer that likes to have fine grained control over these matters and will test which setting "feels" just right.

When I want to make a change to one of my layers I would argue that it is cleaner to make it on the layer level than to apply it application wide via the renderer (and deal with the side effects if they occur).

**Comment by geoloep** [comment]
I created a plugin that realizes the same functionality as I intended with this pull request: [Leaflet.Clicktolerance](https://github.com/geoloep/Leaflet.ClickTolerance).

**Comment by IvanSanchez** [comment]
@geoloep Cool!! Please remember to add the plugin to the plugins list.

**Comment by ValentinH** [comment]
I came across this issue while using paths on Canvas. After looking at the code, I'm wondering why the click detection doesn't use the `tapTolerance` option for the touch case?

**Pull request closed without merging**
