### PR TITLE
GeoJSON layer - this context for option callbacks

### PR DESCRIPTION
**Pull request by tugrul**
Following option callbacks can access GeoJSON layer
instance through this keyword.

- pointToLayer
- onEachFeature
- filter
- coordsToLatLng

### CODE REVIEW

**Comment by tugrul** [comment]
There are some lack about this pull request. I didn't see `geometryToLayer` is static function and i'm going to change this. Please ignore first commit of this pull request.

**Comment by IvanSanchez** [comment]
I cannot see why this is needed. Can you illustrate with a use case?

**Comment by tugrul** [comment]
@IvanSanchez use case https://gist.github.com/tugrul/851ed5fa3e435cf9b940

**Comment by mourner** [comment]
I don't think this is necessary, since you can just use `bind` to set the context whatever you need.

**Comment by tugrul** [comment]
@mourner using `bind` can be workaround but not solution. Also i can set option in initializer and access in this scope. Basic principle: Every callback should have context own instance.

**Pull request closed without merging**
