### PR TITLE
Layer: refactor openPopup/openTooltip: use common function

### PR DESCRIPTION
**Pull request by johnd0e**
`Layer`: refactor `openPopup`/`openTooltip`: use common function `DivOverlay._openOverlay`.

---
This change is [Reviewable](https://reviewable.io/reviews/leaflet/leaflet/6613)

### CODE REVIEW

**Comment by johnd0e** [comment]
Perhaps better name function differently, like `_initOverlay`.

**Comment by johnd0e** [comment]
> maybe `_updateOverlay` would reflect what the code is doing best?

There are already several methods prefixed with `update`, so we need reflect function specific somehow 

Besides, I do not feel that `update` is right word, as this code may be invoked _before_ tooltip opened. It is a sort of preparatory step: here we determine what layer will be set as source, and calculate target latlng.

So may be `_preOpen`?

**Comment by mourner** [comment]
> It is a sort of preparatory step

`_prepareOpen` then? or `_prepareOverlay`

**Comment by johnd0e** [comment]
> `_prepareOpen` then? or `_prepareOverlay`

Ok, PR updated.

I've added one more commit, please check if it's acceptable.

**Pull request merged**
