### PR TITLE
 Grouping layers into categories.

### PR DESCRIPTION
**Pull request by WilliamTokarev**
Added ability to mark a category layers. Name the first layer (specified category) contains the name of the category (before the symbol #).
Example: ... 'SAT#Google': g01, ...

### CODE REVIEW

**Comment by mourner** [comment]
Thanks for the pull! I'm currently not merging any features before Leaflet 1.0 release to allow it to stabilize, but will review this afterwards.

**Comment by IvanSanchez** [comment]
I'd rather see this in a plugin that would subclass L.Control.Layers into something like L.Control.Layers.Categorized.

**Comment by WilliamTokarev** [comment]
Edit small. Whether it is necessary to allocate its plugin. Symbol # is questionable from a layer name (e.g., # to | or @ can be replaced).

**Comment by IvanSanchez** [comment]
Given that users can use the [Leaflet.groupedlayercontrol](https://github.com/ismyrnow/Leaflet.groupedlayercontrol) plugin, I see no reason for this merge request.

**Comment by WilliamTokarev** [comment]
In the Leaflet.groupedlayercontrol plugin "Grouping base layers is not currently supported"...

**Comment by IvanSanchez** [comment]
Then try https://github.com/davicustodio/Leaflet.StyledLayerControl, https://github.com/robbiet480/leaflet-categorized-layers or https://github.com/stefanocudini/leaflet-panel-layers, fix Leaflet.groupedlayercontrol, report a bug/feature request to Leaflet.groupedlayercontrol, or create your own plugin.

**Pull request closed without merging**
