### PR TITLE
docs:plungins.md: add Leaflet-gplaces-autocomplete

### PR DESCRIPTION
**Pull request by Twista**

### CODE REVIEW

**Comment by IvanSanchez** [comment]
Is there a live demo somewhere?

**Comment by Twista** [comment]
nope, there is just example in the repo, but requires google api key for places api

i can add some screenshot to the repository if will help

**Comment by Twista** [comment]
Hello, may i ask how it looks with this PR ? 

there is screen how extension looks/works

info-presentation_map

info-presentation_map

**Comment by IvanSanchez** [comment]
That looks good!

Please make sure to include that image on your README file, so that people visiting your repo can know how the plugin looks.

**Pull request merged**
