### PR TITLE
Plugins: Adds Leaflet.Tilelayer.Colorizr

### PR DESCRIPTION
**Pull request by hnrchrdl**
I wrote a plugin for modifying the colors of tilelayers. Would be happy to add it to the list.

### CODE REVIEW

**Comment by IvanSanchez** [comment]
With other plugins such as the greyscale tilelayer, Leaflet.TileLayer.PixelFilter and L.TileLayer.GL, I don't see much benefit from this one. I guess it'll fit a small niche between those, so let's add it to the list.

**Comment by hnrchrdl** [comment]
This plugin brings great flexibility that is not yet covered with the existing plugins: tweaking contrast, brightness, boosting or swapping color channels and much more. I will add a bunch of demos to show the purpose. Thanks.

**Comment by IvanSanchez** [comment]
I will argue that L.TileLayer.GL does that (and more), and that Colorizr covers browsers without WebGL support. That's why I'm a bit reluctant.

**Comment by hnrchrdl** [comment]
Ok, I was not aware that L.TileLayer.GL could do that, as this is not super obvious from it's name & description. It is your choice after all, thanks again.

**Pull request merged**
