### PR TITLE
Further UX work on the website redesign 

### PR DESCRIPTION
**Pull request by rowanhogan**
Adds main UX aspects of changes made in #3566 to `redesign` branch.

@mourner I've moved the bulk of my UX features over. I didn't include the major design changes I added in the earlier PR, the main focus was the responsive tables, TOC menu and tidying up the existing responsive design.

Also:
- Adds new tutorial thumbnails.
- Updates broken logo images on homepage.

The `redesign` branch probably still needs a little bit of work, but hopefully now my additions/changes are going towards the direction you had in mind. :)

screen shot 2015-06-30 at 1 17 37 am

screen shot 2015-06-30 at 1 15 24 am

screen shot 2015-06-30 at 1 10 30 am

### CODE REVIEW

**Comment by rowanhogan** [comment]
@mourner is viewing on GH with the whitespace ignored enough? 

https://github.com/Leaflet/Leaflet/pull/3569/files?w=false#diff-953f1e5e4b98aed3d5c205372923b86e

Or are you concerned about Git history? I can revert the whitespace updates if you'd like, just let me know.

**Comment by mourner** [comment]
Yes, please revert the whitespace changes. Generally, changing established conventions throughout the whole codebase without getting maintainer's approval first is rude, don't do that. :)

Also, could you break down the changes here into atomic, independent commits? This way I could review and merge them separately, and we'd have a nice commit history.

**Comment by mourner** [comment]
Reviewed the changes — love them!

- Spacing and typography changes look great!
- Happy to see the logo block updated. I've been meaning to redo it with updated assets but it's such a hassle — thanks for putting your time into this. :) We might want to revise the list of logos, but let's keep thta for latter.
- I was not entirely sure about heading and table styling changes in the original PR #3566, but in this branch, they somehow fit much better.
- Still not entirely sure about the dark code blocks — I always have a hard time reading code on dark themes, but maybe that's a personal readability issue. I agree that contrast/scanning is a problem, but maybe we could fiddle with this a bit more — maybe trying a light scheme but with a subtle non-white background, or maybe toning down background on the dark scheme.

Generally, with just a few minor iterations, I think we could merge this pretty soon. :) I wasn't entirely sure about the redesign branch so I left it for better times, but now with your updates I'm more confident that it'll be a big improvement.

**Comment by mourner** [comment]
We probably need some white overlay underneath the submenu:

image

**Comment by mourner** [comment]
I rebased the `redesign` branch to include all commits from the latest `gh-pages`, so you'll have to rebase your changes as well for a clean history.

**Comment by rowanhogan** [comment]
Ah great, I was just looking at that now – I didn't want to miss anything added to `gh-pages` from the last few months :)

I'm going to redo my changes in a nice series of simple commits, will get back to you shortly! I will also fix the issue with the menus.

**Comment by mourner** [comment]
Thanks a lot! When you redo the changes, you can just do `git reset --hard your-new-branch` in this branch afterwards and then `git push --force` to update the current PR so that you don't have to submit a new one.

**Comment by mourner** [comment]
One more thing: table row permalinks on the docs page don't work after your updates.

**Comment by rowanhogan** [comment]
I've now broken it down into smaller commits. I also fixed that issue that was preventing the table row anchors from working.

With regards to the code block styling, I did lighten the background slightly, but if you'd prefer a light theme that's fine, it's easy enough to change.

I've updated [rowanhogan.github.io/Leaflet](http://rowanhogan.github.io/Leaflet/) to be based on the `redesign` branch for browser testing.

**Comment by mourner** [comment]
@rowanhogan looks great! I now see the issue with gray code blocks (looking 1 commit earlier) — they look the same as tables when scanning the reference page. I think a good solution to try would be to make tables white again, just adjust the styling a bit... E.g. here's what I came up with fiddling in devtools a bit:

image

What do you think?

The reason I like white and light backgrounds is that I want the design to keep this feeling of lightness and minimalism which are Leaflet's best characteristics.

**Comment by mourner** [comment]
Merged your commits to `redesign` branch manually, amending the last commit to revert the code style color changes.

**Comment by mourner** [comment]
There are still some problems with the ToC menu:

- the dash overlaying the titles
- weird indentation of all items but the first three

image

**Comment by mourner** [comment]
@rowanhogan I've just sent you an invite to the Leaflet GH team so that you could make minor fixes like the above easier — welcome. :) But make sure to always make PRs for changes that need discussion.

**Comment by mourner** [comment]
Fixed the menu.

**Pull request closed without merging**
