### PR TITLE
Bug fix in Path.setStyle (Issue #6662)

### PR DESCRIPTION
**Pull request by NielsHolt**
Bug fix in Path.setStyle. Fix issue #6662 and #6664

### CODE REVIEW

**Comment by cherniavskii** [comment]
Thanks @NielsHolt
This looks good to me :+1:
Would you mind adding unit tests for each issue to prevent future regressions?

**Comment by chuyelong** [comment]
undefined style causes crash here 
`if (this.options.stroke && style.hasOwnProperty('weight'))`

**Comment by NielsHolt** [comment]
Hi @IvanSanchez 

Will this PR be included in next version? (1.6.1)
Do you need anything from me to include it?

**Comment by IvanSanchez** [comment]
@NielsHolt There's a merge conflict (because https://github.com/Leaflet/Leaflet/commit/ffc280c7b3afc409286e879e81d87c8fb6934513 modified a line too close to your proposed changes). Either read up https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line , or (since the change is very small), check out the `master` branch again and create a new PR.

**Comment by NielsHolt** [comment]
Thanks @IvanSanchez  I will look into it asap

**Comment by NielsHolt** [comment]
This PR has been replaced by #6941

**Pull request closed without merging**
