### PR TITLE
Replace the big HTML list of plugins with structured data and jekyll magic

### PR DESCRIPTION
**Pull request by IvanSanchez**
I felt bothered with the "how can we tell if a plugin is compatible with 0.7/1.0?" and also "what is the name for the npm package of this plugin?", so I decided to experiment making the list of plugins into a data structure, and some jekyll/liquid magic to create the static list.

Kinda addresses https://github.com/Leaflet/Leaflet/issues/3240 , as this would make that simpler.

Results looks good so far. I'm not sure about the badges, or about displaying the `npm install leaflet-plugin` bit. I'm wondering how to add some generic `<script src="https://unpkg.com/leaflet-plugin">` also.
screenshot_20170314_175356

---

Things that need to be resolved/discussed before putting more work on this:

- [ ] How to properly convey compatibility with Leaflet 0.7 / 1.0. The badges seem too intrusive.
- [ ] Replace links to the repo with a github/gitlab/bitbucket logo+link??
- [ ] Replace `npm install foo` with a npmjs/unpkg logo+link??
- [ ] Replace author link with an array of links + logos (github/twitter/whatever)
- [ ] File naming. Do we want one file for all the plugins, or one per plugin category?
- [ ] Create a template for the table (like `docs/_includes/frame.html`), then reuse it once per category
- [ ] Add a field for the software license too? This should have the same concept as debian's "contrib": "promotes or depends on a non-free service or library"
- [ ] Are there logos/badges for licenses?
- [ ] Try a two-row + `rowspan=2` layout, so the rightmost column can be two cells with author on top and badges on bottom

### CODE REVIEW

**Comment by IvanSanchez** [comment]
Note that this is a WIP as I've only worked on just one section.

**Comment by perliedman** [comment]
Great work (as always), @IvanSanchez! I was toying with the same idea a couple of months ago, but never got anything done.

I think the advantages are obvious, and adds flexibility to do lots of interesting things with the plugin page.

A possible downside, though, is that this will make it harder for people to add new plugins: people know how to edit a HTML page, but not necessarily our custom YML format. (Come to think of it, you might see that as an advantage as well :stuck_out_tongue_winking_eye: )

**Comment by perliedman** [comment]
Related: it would be great if the plugin page could also automatically show stars and last activity for each plugin, when hosted on Github. But that is really outside the scope of what you're doing here.

**Comment by IvanSanchez** [comment]
> people know how to edit a HTML page, but not necessarily our custom YML format.

C'mon, it's just copy-pasting a few lines :-P

---

There are a few things I'm not convinced about and would like some input about, I'll leave them as a to-do list.

**Comment by perliedman** [comment]
I rebased this and changed the structure a bit; now the whole plugin page's structure with categories, subcategories and the plugins themselves are all in the `plugins.yaml` file.

I spent quite some time on a script which extracts all the data about the current plugins.

Some things to note:

* The initial "table of contents" still isn't auto generated (not sure how to deal with the columns automatically)
* Some data is missing from my auto-script (no automatic way to know demo link and version compatibility status)
* The structure of the YAML file became pretty messy when it was auto generated; in particular, the order of the category and plugin properties isn't friendly to a human; we should probably clean this up if we expect humans to edit the file

**Comment by perliedman** [comment]
Oh, yes one more thing: the internal links on the page are currently broken.

**Comment by Falke-Design** [comment]
@IvanSanchez do you want to keep this PR open?

**Pull request closed without merging**
