### PR TITLE
Feat(ESmodule): provide an entry file compatible to module loaders

### PR DESCRIPTION
**Pull request by ghybs**
so that application developers can import Leaflet using any module loader (not just Rollup) and benefit from the latter's advantages, typically bundle optimization / tree shaking.

This is a follow-up from https://github.com/Leaflet/Leaflet/issues/5489#issuecomment-313845806

Here is the updated Plunkr demo, using the `index.js` entry file at https://rawgit.com/ghybs/Leaflet/8b7fba889368684c0066bbde151a5979033e4931/src/index.js instead of the inline one in the previous demo version:
https://plnkr.co/edit/987oafSDqBblon8gl0vD?p=info

In the case of **SystemJS**, this module loader automatically detects AMD usage.
Therefore plugins with such AMD wrapper can be used without issue, provided that the application developer imports the modified symbols from `leaflet`.
An easy way to achieve that is simply to import everything into the `L` namespace, in which case we re-create a similar situation as having `L` globally available:
```javascript
import * as L from 'leaflet';
import 'leaflet.featuregroup.subgroup'; // or any AMD-wrapped Leaflet plugin.

// Use as if leaflet and the plugin were loaded through browser <script> tags…
L.featureGroup.subGroup();
```
Demo with plugin: https://plnkr.co/edit/Do6MdN0V8I3e1WFSMrXB?p=preview

Now we should very probably do a similar exercise for other module loaders?

### CODE REVIEW

**Comment by perliedman** [comment]
Ok, so lets see if I understand these changes correctly.

For new modern build systems that understand modules, they will `import` from this new `index.js`, which _just_ exports the Leaflet namespace as an object, but does not set any global, etc.

This will only work with plugins that are written using the same method, that also import Leaflet this way, and doesn't rely on the global `window.L`. However, they can still attach to Leaflet's namespace (since you use `L.featureGroup.subGroup` in your code).

A question regarding the last point, attaching to Leaflet's namespace, is if this is something we want to continue advocating as a "best practice" for plugins? I've really like the "attach to Leaflet's namespace" as long as we used a global (then there's at least only _one_ global). With modules, it occurs to me this is starting to be a bit counter-intuitive rather than helpful. Any thoughts on this?

I think you're right we need to try this out with other module loaders as well, I'm adding those as a checklist here:

* [ ] Webpack
* [ ] Rollup
* [ ] Browserify

**Comment by colbin8r** [comment]
I'd like to weigh on the Leaflet plugin/global namespace issue. I'm writing an ES6 Leaflet plugin now. I wanted both to expose my ES6 modules and follow the best practice of attaching to the global `L`. Here's a gist showing some code that should do that: https://gist.github.com/colbin8r/795c89433a6bc0098cd4df30ccac4e04
(It should probably also check for the existence of a global L now that I think about it... 🤔)

It's been well-established that global variables are a bad practice in general. Also, having Leaflet depend on globals has been a thorn in my side (see #5613). Probably the best solution is to only expose `L` if you know you're in a browser environment (e.g. check for `window` or something).

**Comment by mourner** [comment]
We should definitely do this, although keeping a separate `index.js` for this makes it harder to maintain. @ghybs want to explore if json2module-based solution looks nicer in Leaflet?

**Comment by ghybs** [comment]
Hi @mourner,

As for the entry file, I would see a few possible options indeed:
- Use `json2module` from `d3`, but needs to duplicate data from `package.json` during the build step. Therefore in some cases that data may be missing (directly importing the entry file from a cloned repo, instead of from a built copy like `npm`).
- Import `index.js` in `Leaflet.js`, like a wrapper for Rollup build. A nice advantage is that the `index.js` could be as much lean and compliant with ES modules as possible (but the version issue from previous point could still be problematic), while we still provide some workarounds for the UMD build (global, `noConflict`…)

**Comment by ghybs** [comment]
@perliedman,

> With modules, it occurs to me [attaching to Leaflet's namespace] is starting to be a bit counter-intuitive rather than helpful.

I would even say that keeping the namespace by default totally defeats one of the main points of ES modules! :-) I think modules should delegate naming to consumer code.

> However, they can still attach to Leaflet's namespace […]

Well I think this is actually specific to SystemJS, which automatically detects AMD-wrapped libraries and behaves accordingly. I think there is something similar with Rollup through [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) plugin.

I am trying to come up with a scheme to do something similar as Leaflet for the plugins: having a clean ES module (that does not try to rely on global), with a Rollup build to UMD version, that would behave more or less like currently.
Will post when I have something working.

**Comment by ghybs** [comment]
Here is already a new commit to demonstrate the re-use of `index.js` entry file for ES module in `Leaflet.js` for UMD Rollup build, so that all exports are managed in a single file.

The resulting build is exactly the same.

**Comment by jjimenezshaw** [comment]
@ghybs 
> I would even say that keeping the namespace by default totally defeats one of the main points of ES modules! :-) I think modules should delegate naming to consumer code.

Making a plugin makes sense to do it inside `L` namespace, so it is a bit redundant. However, while making a webpage "using" Leaflet, I would prefer to know what is Leaflet and what is not. Then the namespace makes totally sense for me. Even `Map` or other modules can conflict with my webpage modules (or get mixed in an ugly way). How do I proceed in this case?

**Comment by ghybs** [comment]
Hi @jjimenezshaw,

Thank you for your input!

Please can you kindly clarify the situation(s) you are referring to, so that we make sure we understand each other?
- `import {pluginClass} from 'leaflet-plugin'` (ES6 module)
- `var plugin = require('leaflet-plugin')` (CommonJS)
- `require(['leaflet', 'leaflet-plugin'], callback)` (AMD)
- `<script src="leaflet-plugin.js"></script>` (currently global)

**Comment by jjimenezshaw** [comment]
@ghybs Sorry, I misunderstood something. I can import Leaflet and use it normally with `import L from 'leaflet';` Later I can do `L.map` and other methods as usual (using `L` namespace I mean). Forget my previous post ;)

**Comment by colbin8r** [comment]
@jjimenezshaw Even better, you can import only the parts of Leaflet you actually need:

```js
import { Map } from 'leaflet';
let myMap = new Map(...);
...
```

This allows for you to include in your final bundle or code *only the parts of Leaflet you actually depend on* through a technology called [tree shaking](https://github.com/rollup/rollup#tree-shaking). Since the `Map` module exported by Leaflet probably depends on other Leaflet components, those components are included as well, but you eliminate extraneous code from your final/production build.

**Comment by jjimenezshaw** [comment]
@colbin8r Thanks. But if I want to 'keep' the `L`, how do I do "this"? (because "this" doesn't work)
```javascript
import { Map as L.Map } from 'leaflet'; 
let myMap = new L.Map(...);
...
```
See that I want `L` not only on Map, but on every dependency it imports.

**Comment by colbin8r** [comment]
@jjimenezshaw I'm not sure why you would want to keep `L` other than for visual similarity to existing Leaflet code. If that's the case, then you may want to reconsider because I think Leaflet as a whole is moving away from namespacing everything under a global `L` anyway, so this style will likely change. One of the benefits of using ES6 modules is that you can use call the exports from other modules whatever you prefer.

With your last code example, you don't have direct access to any of the `Map` modules dependencies anyway because they aren't imported into your current scope. If you want access to them, you have to import them yourself.

But to answer your question, you have a few options.

1. Import everything like you were and forget about tree-shaking:
```js
import L from 'leaflet';
let myMap = new L.Map(...);
```

2. Manually namespace it yourself.
```js
import { Map } from 'leaflet';
// note the ES6 object literal here
// https://github.com/lukehoban/es6features#enhanced-object-literals
L = { Map };
let myMap = new L.Map(...);

Let me know if I missed something.

**Comment by jjimenezshaw** [comment]
I like namespaces for libraries. I love it. All my life hearing 'Do not use global variables/functions', and as far as I see, when you import a module you create some stuff in the global scope. It was cleaner when there was only one, `L`.

On the other side, it is great including only what I use, and not everything.

But unfortunately I cannot have both things. It is a pity that I cannot import a module, and directly include it in a namespace I choose (and everything that imports it as well... like `L`).

Anyway, thanks for you help.

**Comment by IvanSanchez** [comment]
Hhhhhmmm. Doesn't https://github.com/Leaflet/Leaflet/pull/6021 supersede this PR?

**Comment by ghybs** [comment]
Hi @IvanSanchez,

Thank you for pointing it out!

Hum indeed, both PR address the same objective.
Having the global export and `noConflict` in Rollup config `outro` (as done in #6021) avoids having to split `Leaflet.js` in 2 chained imports (as done in this PR), at the expense of coding them as strings.

There is still the concern about importing the `version` from `package.json`, but that could be addressed in a separate PR.

I also quite advanced regarding plugins as ES modules and buildable through Rollup.
I will probably post that as a separate thread then.

**Pull request closed without merging**
