### PR TITLE
[hotfix] remove pkg.module

### LINKED ISSUE #6238: ReferenceError: L is not defined adter upgrading to 1.3.2
- Leaflet version I'm using: 1.3.2
- Browser (with version) I'm using: Chrome  67.0.3396.99
- OS/Platform (with version) I'm using: OSX

I have a working Angular/Ionic app with leaflet map. After upgrading from 1.3.1 to 1.3.2, I got this error.

### PR DESCRIPTION
**Pull request by cherniavskii**
Closes #6238

This is a hotfix, but I'm not convinced this is the right way.

### The problem
In #6021 `pkg.module` was introduced (which is good).
But.
[`es` build](https://unpkg.com/leaflet@1.3.2/dist/leaflet-src.esm.js) doesn't expose global variable, which breaks plugins or code that refers to `window.L`.

Furthermore, most bundlers (like rollup, webpack etc.) use `es` bundle if available.
That's why `1.3.2` breaks people's apps.

### The solution
This PR solves a problem described above, but I don't thinks there's any sense in providing `es` bundle, which exposes global variable.

This side-effect (global variable) would break tree shaking, so using `es` bundle over `umd` bundle doesn't make any sense.

We cannot get rid of global variable - see #2364, so Leaflet is not ready for exposing `es` module.

### Summary
IMHO we should revert #6238 and provide only `umd` bundle, as before.

What do you guys think?

@Rich-Harris 
@mourner @ghybs @IvanSanchez @perliedman

### CODE REVIEW

**Comment by Rich-Harris** [comment]
I don't really have a stake in this, but personally I'd argue against going back to using globals in Leaflet itself for the sake of plugins — this is really just a question of dealing with legacy, since modules are now [supported in all browsers](https://caniuse.com/#search=module) (IE11 doesn't count!), and shipping proper ESM has tangible benefits such as treeshakeability.

It's easy enough for an app using those plugins to create `window.L` itself. Could even add a `leaflet/global` module for convenience, which could be used as an alias for Leaflet itself via webpack/Rollup config:

```js
// leaflet/global.js
import * as L from '..';
export * from '..';

window.L = L;
```

**Comment by mourner** [comment]
Yeah, based on the number of responses in that issue, it looks like we should revert and hotfix (so that automatic semver upgrades in people's apps don't break automatically), and consider readding this for a major version (where people will have to upgrade manually). Perhaps together with dropping old IEs.

**Comment by mourner** [comment]
> personally I'd argue against going back to using globals in Leaflet itself for the sake of plugins

@Rich-Harris I completely agree; the issue here is that a breaking change is happening in a patch release, which is not right even if the change itself is great.

**Comment by cherniavskii** [comment]
@mourner done

**Comment by cherniavskii** [comment]
@Rich-Harris 
> It's easy enough for an app using those plugins to create window.L itself

Yeah, that's probably the way to go. Thanks for your feedback!
But in this case, if one's using at least one plugin which needs `window.L` exposed, then Leaflet wouldn't not be treeshaken? Am I right?

**Comment by mathe42** [comment]
Solution for rollup: https://www.npmjs.com/package/@ec-nordbund/rollup-plugin-leaflet

**Pull request merged**
