### PR TITLE
Fixed dead link #4899

### PR DESCRIPTION
**Pull request by JonasDralle**
this takes care of the broken link to this exact branch

issue #4899

have fun

### CODE REVIEW

**Comment by JonasDralle** [comment]
This is a very minor fix
But i am very new to the open source community on github so i'll keep my contributions small :wink:

**Comment by yohanboniface** [comment]
Good catch!
But the Leaflet site is now direclty managed in `master` branch, inside the docs/ folder instead.

**Comment by JonasDralle** [comment]
404 anyway

**Comment by JonasDralle** [comment]
should i make a pullrequest for master?
or do you guys want to do it?

Don't know what you prefer

**Comment by JonasDralle** [comment]
i created an pull request for master
I thought it was bad practice to push directly to master

**Pull request closed without merging**
