### PR TITLE
Do not use an incorrect comparison of strings with an integer.

### PR DESCRIPTION
**Pull request by OriginalSin**
Hi Guys!
Do not use an incorrect comparison of strings with an integer.

### CODE REVIEW

**Comment by IvanSanchez** [comment]
Hi @OriginalSin , 

Why is that comparison incorrect? Under which circumstances does it provoke an error? When proposing a change, it's always better to explain what problem you're trying to solve, or what use case is improved by it.

Also note that we enforce usage of `===` in the linting rules, so changing this actually breaks the build.

**Comment by OriginalSin** [comment]
Because this code print `false`:
var hash = {};
hash[5] = true;
for( var key in hash) {
  console.log(key === 5)
}

**Comment by OriginalSin** [comment]
Also check the _removeTilesAtZoom, which does not work if the parameter is a string.

**Comment by IvanSanchez** [comment]
But how does this fail when using a leaflet map with a `TileLayer`?

**Comment by OriginalSin** [comment]
I think if you zooming very active.

**Comment by cherniavskii** [comment]
@OriginalSin can you please provide an example, which reproduces the issue solved by this PR?

**Comment by OriginalSin** [comment]
@cherniavskii Hi, I can only suggest inserting `console.log` or `alert` in the code:

_removeTilesAtZoom: function (zoom) {
       for (var key in this._tiles) {
            if (this._tiles [key] .coords.z! == zoom) {
               continue;
            }
            console.log ('is this code execute sometimes ????', this._tiles [key] .coords.z, zoom, this._tiles [key] .coords.z === zoom);
            this._removeTile (key);
       }
},

and try to find such a case when we see the message.
I say that **this function does nothing - never**.

**Comment by OriginalSin** [comment]
Yes, I understand that.
The only consequences (that I think it was possible by this code) is that with active zooming on DOM there are left containers from severa zooms.
default

**Comment by johnd0e** [comment]
> Because this code print `false`:

@OriginalSin
Nice catch!

But this wrong pattern seems common in Leaflet, so we need to fix all such cases.

**Comment by johnd0e** [comment]
Cleaner solution would be using [`Object.keys()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) instead, but it is available only since IE 9.

**Comment by mourner** [comment]
Superceded by #7123

**Pull request closed without merging**
