### PR TITLE
Leaflet server import

### LINKED ISSUE #6331: Leaflet doesn't play nice with a server-side environment due to window references in utils
## How to reproduce
`import L from 'leaflet'` in a nodejs environment. Because there are naked references to [window](https://github.com/Leaflet/Leaflet/blob/9fda888df2791ca0df6f182a9d91d393ee49034c/src/core/Util.js#L214) [attributes](https://github.com/Leaflet/Leaflet/blob/9fda888df2791ca0df6f182a9d91d393ee49034c/src/core/Util.js#L217) in the [utils file](https://github.com/Leaflet/Leaflet/blob/9fda888df2791ca0df6f182a9d91d393ee49034c/src/core/Util.js#L218), this will throw an error.

## What behaviour I'm expecting and which behaviour I'm seeing
It makes sense that this library is oriented around the browser, since that's typically where you're going to find this code, and the functionality doesn't make sense if you're running it in a Node environment.

However!

This makes things very difficult for server-side rendering using things like `react-leaflet`, since simply importing the package is enough to make this throw errors.

## Minimal example reproducing the issue
`import L from 'leaflet'` in a nodejs environment.

### PR DESCRIPTION
**Pull request by cherniavskii**
Closes #6331

Hi,
After discussions in #6332 and some research, I've found a simple solution for #6331 

This PR adds an intro to Leaflet UMD bundle, so importing Leaflet in non-browser environment won't break the app - which is pretty important for universal (isomorphic) applications.

Note, that this change affects only UMD bundle (which is used by most users).
I don't think there's a simple solution for ESM bundle.

I've added a regression test, and had few approaches to integrate it with our Travis CI configuration, but with no success :/
That test needs to be executed on ready UMD bundle (i.e. after `build` script), but `after_success` hook ignores non-zero exit codes and shows passing build even if test exited with code 1.
I guess, I'll leave that part uncovered for now.

Any feedback would be appreciated! :)

### CODE REVIEW

**Comment by tstirrat15** [comment]
This approach makes sense as a direct fix for imports breaking on the backend. I've done similar things to other libraries with browser dependencies, but on the Webpack side instead of the Rollup side.

There should probably be some accompanying doc changes - there are some features, like [LatLng](https://leafletjs.com/reference-1.3.4.html#latlng)s, that seem like they should work all right in a server environment, since they're not tied to DOM manipulation at all, but that wouldn't work because the code isn't exported.

It seems like this will be a process, though, so that could be for future work.

**Comment by MrDigii** [comment]
Is it intended to merge this pull request to a new leaflet release any time soon?  This request is open since Oct. 2018... I need this feature to use it in my npm library that is imported into a Nextjs Project later. :/

**Comment by Falke-Design** [comment]
@MrDigii can you please provide a sample what you would do if you can import Leaflet?

**Comment by jonkoops** [comment]
I'd recommend that you lazy load Leaflet on the client and not initialize it on the server. You can find more motivations on why we don't support these kind of things under #6332.

**Pull request closed without merging**
