### PR TITLE
Add a plugin to add WMTS services

### PR DESCRIPTION
**Pull request by GeoportalPL**
Add a plugin to add WMTS services

### CODE REVIEW

**Comment by GeoportalPL** [comment]
Plugin.md was updated, We added new plugin Leaflet.wmtsproj.

**Comment by GeoportalPL** [comment]
Hello,
Of course, adding to the top of the list was not intentional, as was the demo link. I will correct it, the plug should be at the end, thanks for the remark. We haven't added the plugin to the NPM yet, everything in front of us is our first plugin.

**Comment by GeoportalPL** [comment]
We changed the order in the list, until we created a demo, the link was deleted.

**Comment by cherniavskii** [comment]
Hmm, I just realized that you accidentally added a copy of `plugins.md` file to the repo, so please remove it

**Comment by GeoportalPL** [comment]
I do not fully understand. I added plugins.md to Leaflet which was fork to my account. Which file you are talking about?

**Comment by cherniavskii** [comment]
https://github.com/Leaflet/Leaflet/pull/5943/files - that's your changes.
You modified `docs/plugins.md` file, and also added `plugins.md` file to the Leaflet's root.
What you supposed to do is to modify `docs/plugins.md` only.
Just remove `plugins.md` from the root, commit and push it to your fork's master branch.

**Comment by GeoportalPL** [comment]
I deleted the redundant file, now everything should be ok.\

**Pull request merged**
