### PR TITLE
test(GridLayer): add debugging logs

### PR DESCRIPTION
**Pull request by ghybs**
Hi,

This is a dummy PR to launch Travis CI and try to debug the currently failing tests:
https://travis-ci.org/Leaflet/Leaflet/jobs/396715939

This PR currently adds debugging logs to try to determine where Travis fails with Firefox, whereas it works locally.

### CODE REVIEW

**Comment by ghybs** [comment]
Damn it works…

I would have preferred understanding why it failed.
If the test in question (introduced in PR https://github.com/Leaflet/Leaflet/pull/6201) fails again, I might simply remove it, as it is supposed to be similar to the previous one, but without trying to fake the time…

**Comment by ghybs** [comment]
Hum it is definitely inconsistent:
https://travis-ci.org/Leaflet/Leaflet/builds/396846693

**Comment by ghybs** [comment]
All right, looks like PR test and `master` test get different setup:
- PR test: https://travis-ci.org/Leaflet/Leaflet/builds/396844166
- `master` test: https://travis-ci.org/Leaflet/Leaflet/builds/396846693

The only difference I could spot was that the `master` test gets a BrowserStack configuration:
```bash
Setting environment variables from repository settings
$ export BROWSERSTACK_USERNAME=[secure]
$ export BROWSERSTACK_KEY=[secure]
```

However the Travis [configurations](https://travis-ci.org/Leaflet/Leaflet/jobs/396846694/config) are identical in both cases.

Please who could point me to some direction to investigate the Travis and BrowserStack config?

This _could_ be related to issue https://github.com/Leaflet/Leaflet/issues/5999

**Comment by cherniavskii** [comment]
@ghybs we don't actually use Browserstack, so it shouldn't impact the CI :/

**Comment by ghybs** [comment]
Closed by #6221

**Pull request closed without merging**
