### PR TITLE
Zoom anim fires 'transitionend' event handler on a timer

### PR DESCRIPTION
**Pull request by IvanSanchez**
Like #3894, but porting @mourner's code from https://github.com/Leaflet/Leaflet/commit/91477588faa44e2b266d86a5a44cb98490244d39

### CODE REVIEW

**Comment by mourner** [comment]
This caused a tile loading race condition on iOS that I had to hack-fix with https://github.com/Leaflet/Leaflet/commit/3e200bed22bdb1f59e54f37c93b4fce034fd7ee4. Should we port that here as well?

**Comment by IvanSanchez** [comment]
@mourner Are you sure that iOS race condition is still present in `master`?

**Comment by mourner** [comment]
Not sure, it's hard to reproduce. We can risk it and not port and then see if anyone complains, but that's not a perfect approach. :(

**Comment by IvanSanchez** [comment]
More hackish than I would like, but OK.

**Pull request merged**
