### PR TITLE
Fix Bug: permanent & sticky tooltip

### PR DESCRIPTION
**Pull request by Falke-Design**
Fixes bug: if tooltip is sticky and permanent it was not following the mouse https://github.com/Leaflet/Leaflet/issues/7201#issuecomment-655746354

Demo: https://plnkr.co/edit/dPPR4QQ4rBwVwQH2

Removed from the PR #7406

### CODE REVIEW

**Comment by johnd0e** [comment]
> Fixes bug: if tooltip is sticky and permanent it was not following the mouse [#7201 (comment)](https://github.com/Leaflet/Leaflet/issues/7201#issuecomment-655746354)

Seems provided link is not relevant here

**Comment by johnd0e** [comment]
Please add plunkr to illustrate the issue.
Also, we need unit tests for this.

**Comment by Falke-Design** [comment]
@johnd0e plunkr and tests added

**Comment by johnd0e** [comment]
> Fixes bug: if tooltip is sticky and permanent it was not following the mouse

Just thought: the bug might be fixed easier, by documenting that such option combination is not allowed.

Is there useful case for sticky+permanent, which not looks ugly?

**Comment by mourner** [comment]
> Just thought: the bug might be fixed easier, by documenting that such option combination is not allowed.

Easy enough in the current form, so I think it's not a big deal to allow it. Never know how people might make use of it.

**Review by mourner — APPROVED** [review]

**Pull request merged**
