### PR TITLE
Add new plugin: Leaflet.CoordinatedImagePreview

### PR DESCRIPTION
**Pull request by utahemre**
This plugin can show coordinated images in a list and in lightbox. We are using some of our projects. This can be useful to others.

### CODE REVIEW

**Comment by IvanSanchez** [comment]
This plugin is maybe a bit too specific, but looks good! :-)

@utahemre Have you tried this plugin with Leaflet 1.0.0-beta2? We'd like to make sure new plugins are compatible with the 1.0.0 branch.

**Comment by utahemre** [comment]
I have not tried with Leaflet 1.0.0-beta2. But I am going to try today and if any problem occurs, I will fix it and make compatibale with 1.0.0 branch.

**Comment by IvanSanchez** [comment]
@utahemre :+1:

**Comment by utahemre** [comment]
I have tested with Leaflet 1.0 beta 2 and works well.

**Comment by IvanSanchez** [comment]
@utahemre And I see you added a note in your readme file. Perfect! :-)

**Comment by utahemre** [comment]
Here is just one perfect thing. This is LeafletJS. LeafletJS gives direction to my business life.

**Pull request merged**
