### PR TITLE
Update plugins.md

### PR DESCRIPTION
**Pull request by sandropibia**
I'll glad to add my plugin to the community

### CODE REVIEW

**Comment by cherniavskii** [comment]
Hi Sandro,
Thanks for creating a plugin!

Could you please provide a link to demo page which demonstrates the plugin in you readme file?
I saw an there already is an `example` folder in your repo, looks like you can easily use it with [Github Pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/).

Also, placing your plugin on the beginning of the table doesn't seem fair in relation to plugins, added earlier ;)

**Comment by sandropibia** [comment]
Just added a link to the index.html form the example directory

thanks..

**Comment by sandropibia** [comment]
Must I change the table order or must i do that?

Please let me know, this the first time i'm working with github and forks.

Thanks...

**Comment by cherniavskii** [comment]
I think it would be fair to add it in the end of a table.

From a fast look, it looks like your demo works only if selecting poligon and throws errors when trying to get features, which are not polygons. Could you update demo in order to make it more "demonstrative"? If there are different types of layers on the map, it should work with any of them.

Also, `get features` button changes the color of selected layer, so maybe it should be renamed to be more explicit?
`delete area(s)` button seems to remove all selected areas.
Some of API methods are not demonstrated at all.

I have some comments for API docs too:
- missing info if `getFeaturesSelected`'s argument is required/optional
- `doRemoveAllSelection` - name looks weird, maybe something like `removeAllSelections` would be better? Same with `doRemoveLastSelection`.
- `LatLng` & `getBoundsAreaLatLon` naming conflict

So I think you should improve demo page and API documentation before we can add your plugin to a list.
Please take a look at [Leaflet Plugin Guide](https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md), it may help a lot.

**Comment by sandropibia** [comment]
Hi Andrew,

Thanks for the feedback. I have already put my plugin at the back.

This week I'll working on the following:
* update demo for:
  a. getting features 
  b. manupulating features once the user has access to the layers selected
* demonstrate all API methods
* naming conflict on method -> changing the name of the method
* more sophisticated names for methods removing selections
* improving demo page and API doc in the readme

When I'm done how can I contact you, so you can have a review again?

Thanks in advance.

**Comment by cherniavskii** [comment]
Sure, just a leave a comment here any time :)

**Comment by sandropibia** [comment]
Hi Andrew,

Can you have a look again on the project and give me feedback if necessary .

I have updated the demo page and the readme

Thanks in advance.

greets,
Sandro

**Pull request merged**
