### PR TITLE
Use passive event listeners

### PR DESCRIPTION
**Pull request by danielkorte**
Even though Leaflet does call preventDefault this makes it explicitly so and thus passes Lighthouse testing. #5004

### CODE REVIEW

**Comment by danielkorte** [comment]
Updated!

**Comment by danielkorte** [comment]
Good call. Updated to include a passive events support check. Support function stolen from [Modernizr](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/dom/passiveeventlisteners.js).

**Comment by mourner** [comment]
Thanks!

**Comment by zipzit** [comment]
~~Hmmm.  I'm running this change (via build from source) I've verified that my cloned content has the lines shown here, but I'm just not seeing the expected results.  Is it possible that the changes made to src/core/Browser.js , src/dom/DomEvent.DoubleTap.js, src/dom/DomEvent.js aren't propogating over to the dist folder correctly after `$ npm install` and `$ npm run build` ?~~

Oops.  I didn't correctly clear Safari cache for local network testing.  Scratch that.  (I'm leaving my comment in, for anybody else who gets stuck in the same place...)

This update totally fixed my issue of missing tiles on mobile browser.  Many thanks to @danielkorte and support folks.

**Comment by sk33lz** [comment]
Would you be able to tag a new release with this fix? The latest release, 1.5.1, does not include this, so it's not available on any CDNs.

**Comment by iamandrewluca** [comment]
@mourner any ETA when a new release will be made? Thanks!

**Comment by gacallea** [comment]
@danielkorte thanks for the inclusion in 1.6.0 :)

however, I still get a lighthouse error as leaflet doesn't seem to be using passive listener. is there anything I am missing that I need to add to my maps script? or should this work by default?

please and thank you

**Comment by mourner** [comment]
Heads up that this wasn't actually working until #6930

**Comment by gacallea** [comment]
> Heads up that this wasn't actually working until #6930

does this mean we have to wait for 1.6.1? (I'm confused sorry).

**Comment by Ivan-Perez** [comment]
It was actually working in modern browsers, and in older ones there may be some unwanted behaviour because the code always tries to use passive events without checking browser support of that feature.

**Comment by gacallea** [comment]
> It was actually working in modern browsers, and in older ones there may be some unwanted behaviour because the code always tries to use passive events without checking browser support of that feature.

I see, but I have the issue on modern browsers (I don't use old browsers at all).

**Comment by xstable** [comment]
I had the same issue on 1.6.0 within Gatsby: 
image

Can be tested here: https://onepager.erfolgsbeginn.de/
It's part of gatsby, so don't worry about the filename. Look at it source and beautify the contained js, and you see thats leaflet.

**Comment by johnd0e** [comment]
> I had the same issue on 1.6.0 within Gatsby:

You should try latest `master`, it is more recent.

**Pull request merged**
