### PR TITLE
Cancel http requests for outdated tiles

### PR DESCRIPTION
**Pull request by jbccollins**
#5609

### CODE REVIEW

**Comment by mourner** [comment]
I have a feeling we had this logic before but removed it for some reason. Worth digging the history

**Comment by jbccollins** [comment]
@mourner There is a similar line in the ```_abortLoading``` function. @perliedman and I had a discussion on [the issue](https://github.com/Leaflet/Leaflet/issues/5609) about why I did not use or add anything to the ```_abortLoading``` function. Is this what you are referring to?

**Comment by perliedman** [comment]
@mourner looks like you have a good memory: #137 - specifically these changes look related: https://github.com/Leaflet/Leaflet/commit/5f07e8bfc24fdc5e097974a051bc64b9ac82c3eb and https://github.com/danzel/Leaflet/commit/0b913df152a6763f2cacfdf867ddd7a677735fde

Don't know if these are still applicable, it looks like we don't do any checks for `Browser.android` anywhere in the code these days. I would also be surprised if this happens on Chrome/Android, so just checking the Android platform would not be ideal.

So, if we think this is still something we need to guard against, maybe add a new `Browser` check for the old Android only browser and add checks against this before setting `emptyImageUrl`?

**Comment by perliedman** [comment]
@jbccollins sorry for keeping this waiting.

What I mean is that on Android, we should not cancel requests is this is the native Android browser (not Chrome, not Firefox, etc.). Not sure how we best detect that, but hopefully there's a way.

**Comment by perliedman** [comment]
So, I merged this - if someone has an actual device with a stock Android browser, I'd very much like a test to see if this works, and if `L.Browser.androidStock` is actually set correctly - coding in the dark here.

**Pull request merged**
