### PR TITLE
docs: control-attribution-prefix may be `false`

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by johnd0e** [comment]
Wrong place to fix: these *.html are autogenerated from source files.

**Comment by simon04** [comment]
I know. That's why I've updated  the source file `src/control/Control.Attribution.js` as well.

**Comment by johnd0e** [comment]
@simon04

**Comment by simon04** [comment]
Sorry, but no. I'm not interested in revising and worsen this PR after 13 months.

**Pull request closed without merging**
