### PR TITLE
Fix Missing Tiles Error #5381 While Maintaining Zoom Experience #5622

### LINKED ISSUE #5381: Missing tiles after fast zoom in and out with wouse-wheel
I'm experiencing missing tiles when i zoom in and out on the map. I first thought it's an issue with my tile-provider. But after extensive tests i can reproduce it with any Leaflet map and any provider. It's a bit tricky to provoke this though.

## How to reproduce

- I've tested it with LL 1.0.3, and the current trunk
- I can reproduce it with Chrome, FireFox and Edge on Windows 10
- I can reproduce this with a zoom-gesture on my notebook and a real mouse on my PC
- I even can reproduce it with the Leaflet quickstart sample http://leafletjs.com/examples/quick-start/example.html:
- First zoom out to world view.
- Then zoom in very fast with the mouse-wheel
- Immediately afterwards zoom out two wheel-clicks.

You need the right timing to get this result, i manage this about 20% of the time. All i can see is that the missing tile isn't even requested (using fiddler).

missing-tiles

### PR DESCRIPTION
**Pull request by oliverheilig**
Ok,

i reverted the changes from #5431 and tracked down the true error of #5381: on _abortLoading() the incomplete tiles were removed as DOM-element, but not from the _tiles collection, which left them in a kind of zombie-state. So this now fixes #5381 while maintaining the behaviour mentioned at #5622.

You can test the (hopefully final) version here: http://176.95.37.29/vectortest/missing-tiles-fixed3.html

Hope everyone is happy now :sweat_smile:

### CODE REVIEW

**Comment by perliedman** [comment]
@mourner if you have the time, could you check that this looks sane to you as well?

**Comment by perliedman** [comment]
By accident, I stumbled upon this old comment from myself a couple of years ago: https://github.com/Leaflet/Leaflet/issues/3002#issuecomment-62960089

> Shouldn't the tiles be removed from the _tiles cache when they're aborted?

Looks like we've gone a long way to find out that yes, they probably should. :smile:

**Comment by perliedman** [comment]
Merging this and hoping for the best.

Thanks again, @oliverheilig. Sorry this has dragged out for a while, I forgot about this still being open during my vacation. It would have been great if this had been merged before 1.2.0...

**Comment by theashyster** [comment]
@perliedman I remember this post http://leafletjs.com/2016/09/27/leaflet-1.0-final.html and the part about new release cycle and I was really excited that you guys decided to switch the mindset to have shorter release cycles and smaller bugfix releases. So maybe after a week or two it would be a perfect time to do a release for version `1.2.1`.

It really is much more fun when new releases comes out more often and the bugs are squashed. Then you are able to remove those ugly hacks you have added just for the sake of fixing things till the next release of the library you use.

Keep up the good work 👍

**Pull request merged**
