### PR TITLE
Better check for undefined variable

### PR DESCRIPTION
**Pull request by mathiasrw**
Updated a single statement to the fastest way to check for undefined variable

### CODE REVIEW

**Comment by IvanSanchez** [comment]
How much faster is this, then?

**Comment by mathiasrw** [comment]
Donno - and as jsperf.com is not up i wont find out today. 

Feel free to reject if you think its a silly change.

**Comment by IvanSanchez** [comment]
The current way is due to a 4-year-old commit (https://github.com/Leaflet/Leaflet/commit/50c6c480b4f638ec31a74600edca0da28212a333), with the purpose of re-defining `undefined` in a closure, seemingly for helping a uglifier make files smaller. It should be worth it to run a few tests to see if there is indeed a speed improvement. If not, the current code will provide smaller file sizes.

**Comment by mathiasrw** [comment]
I see - its actually the point then...

Ill close the PR for now and will come back if I find hard evidence of speed...

**Pull request closed without merging**
