### PR TITLE
Drop ESM entrypoint from package

### PR DESCRIPTION
**Pull request by jonkoops**
Removes the ESM entrypoint from the package file, as this is causing too many compatibility issues with certain bundlers/tooling.

### CODE REVIEW

**Comment by Falke-Design** [comment]
@jonkoops Tests are failing

**Comment by jonkoops** [comment]
Looks like I forgot to update the build config, should be good now.

**Review by Falke-Design — APPROVED** [review]
Looks good, but I can't test it local.

Maybe you can try it out with one of the reported issues? If not already done

**Review by mourner — APPROVED** [review]

**Comment by jonkoops** [comment]
I'm going to revert the entire commit, that way we can be sure that things will continue working as expected.

**Pull request merged**
