### PR TITLE
Added L.Path.Drag

### PR DESCRIPTION
**Pull request by w8r**
It's a dragging interaction support(extension) for vector shapes. Consistent with Marker.Drag interaction and events. It also adds matrix transformation support to SVG/VML renderers, which can be used for other transformations - skew/scale/etc. As the matter of fact, I think this particular thing could make a good part of Leaflet core functionality.

### CODE REVIEW

**Comment by mourner** [comment]
Not necessary in the core. It's extremely rare to need vector shape dragging, and things like this are usually covered by sophisticated drawing/editing plugins like Leaflet.draw.

**Comment by w8r** [comment]
No, not the dragging, I agree, I meant the [SVG/VML matrix transformations](https://github.com/w8r/Leaflet.Path.Drag/blob/master/src/Path.Transform.js), on top of which things like that could be built. But of course, it's up to you to decide. Thanks for the consideration

**Comment by mourner** [comment]
@w8r oh wow, didn't notice that! I think this would work well as a separate plugin for future Leaflet 1.0 version , with Canvas support baked in too.

**Comment by w8r** [comment]
Ok, thanks, I'll look into it and will try to have it ready then. Good point about canvas renderer. I've already proposed that as a part of Leaflet.draw as well.

**Pull request merged**
