### PR TITLE
plugin: leaflet-layervisibility

### PR DESCRIPTION
**Pull request by phloose**
With reference to #4 and some comments (https://github.com/Leaflet/Leaflet/issues/4#issuecomment-783443266, https://github.com/Leaflet/Leaflet/issues/4#issuecomment-784326375, https://github.com/Leaflet/Leaflet/issues/4#issuecomment-787087842) please update the plugins list with the link to the [leaflet-layervisibility](https://github.com/phloose/leaflet-layervisibility) plugin.

### CODE REVIEW

**Comment by phloose** [comment]
Any chance this will ever be merged 😄?

**Comment by johnd0e** [comment]
@phloose 
Please resolve conflicts

**Review by jonkoops — APPROVED** [review]

**Comment by phloose** [comment]
> @phloose 
> Please resolve conflicts

Resolved

**Review by mourner — DISMISSED** [review]
Please fix the formatting so that it consistently uses tabs.

**Comment by phloose** [comment]
> Please fix the formatting so that it consistently uses tabs.

@mourner fixed for the part that i added to plugins.md. I saw other parts in that file that don't use tabs

**Review by johnd0e — APPROVED** [review]

**Review by jonkoops — APPROVED** [review]

**Pull request merged**
