### PR TITLE
Add support `{-y}` for TileLayer

### PR DESCRIPTION
**Pull request by ShivangMishra**
modified TileLayer::getTileURL to support {-y} syntax from within infinite coordinate systems. 
The change is safe - the only new behavior is supporting {-y} in some cases which previously were unsupported. 

Fixes: #8395

### CODE REVIEW

**Review by Falke-Design — CHANGES_REQUESTED** [review]
I didn't checked the code but a test is needed anyway

**Comment by ShivangMishra** [comment]
@Falke-Design  I need to add a test ?

**Comment by Falke-Design** [comment]
For some reason there was a expliciet test for `{-y}` to be not set on infinite crs (this is also then one who is failing):

https://github.com/Leaflet/Leaflet/blob/c33a57ca3a59c25f8874d09aec5fa2f1c6a98e5f/spec/suites/layer/tile/TileLayerSpec.js#L327-L345

**Comment by ShivangMishra** [comment]
@Falke-Design This is what I understood - 
In the issue #4338 , the problem was that TMS "**needs an upper bound for the CRS's Y coordinate, to be able to flip the tile row**". In the case of infinite crs, we don't have an upper bound, that's probably why they added the check on {-y}.
 In our case, **we don't use the upper bound**, we simply set **{-y} = (-1 * coords.y) - 1**.

**Comment by Falke-Design** [comment]
@mourner @IvanSanchez maybe you can take a look into this. The tile and rendering logic is still pretty hard for me

**Comment by ShivangMishra** [comment]
@Falke-Design I reforked this repo. Should I open a new PR for this issue #8395 ?

**Comment by Falke-Design** [comment]
@ShivangMishra go for it

**Pull request closed without merging**
