### PR TITLE
Pan map on marker drag at the edges

### PR DESCRIPTION
**Pull request by cmulders**
Hi,
As discussed in #3572 auto panning at the edges by markers is not supported.

I also gave it a shot and found a solution by giving the `L.Draggable` object a context when a marker is initialized (the map). It works pretty good and the marker stays at the cursor while panning. I am not aware of the current implementation details of `L.Draggable` and probably the code that I added should be in a plugin or extended class.

I tried to minimize the impact on the core code and therefore it uses the event handlers to check when to pan etc. The code could be implemented in `L.Marker.Drag` or an extension of that class.

An example is available in the folder `debug/map/markers-autopan.html`.

### CODE REVIEW

**Comment by mourner** [comment]
Thanks for the PR. I'll follow up after a review.

**Comment by kaynz** [comment]
@mourner, is this ready to be merged?

**Comment by TimMcCauley** [comment]
@cmulders I got your jsfiddle to work with Firefox, however I'm experiencing difficulties with webkit as ``` e.originalEvent``` is undefined:

``` e.originalEvent``` in Chrome:
``` Object {type: "drag", target: o.C…s.e…d.e} ``` 

``` e.originalEvent``` in Firefox:
``` Object { originalEvent: mousemove, type: "drag", target: Object, latlng: Object } ``` 

Have you got any ideas how to fix this ? Thanks a bunch ,Tim

**Comment by cmulders** [comment]
@mourner Any thoughts for possible implementation of making L.Draggable map or context aware? 

In my opinion is the current implementation hacky. L.Draggable should be unaware of any L.map and only focus on pure DOM manipulation. 
However if a callback or response to the 'predrag' and 'drag' events of L.Draggable could be made,  updating the position information, the map panning handling could be done in L.Marker.Drag instead of in L.Draggable, keeping it clean and tidy without any reference to a 'map' of some sort.

In base Leaflet this functionally is not really required (map panning while dragging a marker), but in drawing plugins this feature or callback point could be very handy to have.

**Comment by TimMcCauley** [comment]
@cmulders we are using this in http://openls.geog.uni-heidelberg.de/openrouteservice-3.0/ and it's working stable, thanks for this.
@mourner I was actually wondering when and if this will be merged into the live branch?

**Comment by m314** [comment]
+1

**Comment by perliedman** [comment]
Closing this in favor of the recently merged #5651.

**Pull request closed without merging**
