### PR TITLE
add ScrollWheelZoom handler enableCenter

### PR DESCRIPTION
**Pull request by dchernyavsky**
Adds handler enableCenter to able to set ScrollWheelZoom option to 'center'

### CODE REVIEW

**Comment by jonkoops** [comment]
Could you provide an example of what this trying to fix or accomplish?

**Comment by dchernyavsky** [comment]
Need to change scrollWheelZoom dynamically, but changing prop not working without re-load component.
image

Now working (and bad) solution is re-load MapContainer component
image
image

Better way change parameters dynamically with handlers like here
image

But exist handlers for scrollWheelZoom sets value only to true or false, not 'center'

**Comment by dchernyavsky** [comment]
Another way to solve this problem is re-declare exist handler enable() to be able pass argument:
enable(value = true) {
		if (this._enabled === value || value !== true && value !== 'center') { return this; }

		this._enabled = value;
		this.addHooks();
		return this;
	},

**Comment by Falke-Design** [comment]
@dchernyavsky just overwrite the map options: `map.options.scrollWheelZoom = 'center'`

**Pull request closed without merging**
