### PR TITLE
Experiments using a big background photo of leaves for the pages.

### PR DESCRIPTION
**Pull request by IvanSanchez**
TODO: 
* [x] Retouch the image, make the branch more prominent
* [ ] Cut into tiles
* [x] Set maxBounds dinamically with getBoundsZoom so some image will always be seen.

### CODE REVIEW

**Comment by mourner** [comment]
WTF, I thought that was a joke! 
btw the page doesn't work for me :) no image visible and scrolling is broken.

**Comment by IvanSanchez** [comment]
@mourner It works better if I remember to upload the background image :-D

leaflet-redesign

**Comment by mourner** [comment]
It's fun, but I think it's too much :)

**Comment by IvanSanchez** [comment]
Let's see if either @rowanhogan or @jieter have any comments on this.

**Comment by jieter** [comment]
Hmm, I think I agree with @mourner. Fun for once and then only distracting every time you need the API docs.

**Comment by rowanhogan** [comment]
I like the idea, but I agree with @mourner that the site should be kept clean and minimal.

**Comment by IvanSanchez** [comment]
> I think it's too much :) 

> I agree with @mourner

> I agree with @mourner

okay2_kindledx

**Pull request closed without merging**
