### PR TITLE
Docs(home): add OSM logo to "trusted by the best" section

### PR DESCRIPTION
**Pull request by astv99**
Previous pull request was closed; submitting this new one as a fix for issue #6271. Added new class "logo-openstreetmap" to docs/docs/css/main.css, new link element to docs/index.html, and the official OpenStreetMap logo to the bottom of docs/docs/images/logos.png. All tests via "npm test" passed.

### CODE REVIEW

**Comment by mourner** [comment]
Can you show the screenshot of how that section looks now?

**Comment by astv99** [comment]
Posting screenshot as requested: 
leaflet_issue_6271

**Comment by ghybs** [comment]
Fix #6271

**Comment by matkoniecz** [comment]
Thanks!

**Pull request merged**
