### PR TITLE
Update L.Util.formatNum rounding

### LINKED ISSUE #6586: L.Util.formatNum round
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Environment**
- Leaflet : 1.3.1 & 1.4.0
- Browser : Firefox 66 & Chrome 73

**To reproduce**
```
L.Util.formatNum(1.005, 2)
> 1
// Returns 1 instead of 1.01

L.Util.formatNum(-1.4837191022531273, 18) 
> -1.4837191022531275
// Returns -1...75 instead of -1...73
```

The way `formatNum` performs rounding can result in unexpected changes to coordinates.
For example :

```
L.GeoJSON.latLngToCoords({  lng: -1.4837191022531273, lat: 43.49222084042808 }, 18)
> [-1.4837191022531275, 43.49222084042808]
```

The precision argument for `latLngToCoords` is not documented, but it may be.
I play with french cadastre, and such approximation leads to various mistakes.

**Solution**

According to this article on [stackoverflow](https://stackoverflow.com/questions/11832914/round-to-at-most-2-decimal-places-only-if-necessary), this rounding method should be better :
```
L.Util.formatNum = formatNum

function formatNum(num, digits) {
  return +(Math.round(num + ('e+' + digits)) + ('e-' + digits))
}
```

### PR DESCRIPTION
**Pull request by inkstak**
Fix #6586

### CODE REVIEW

**Comment by inkstak** [comment]
Also, I've updated documentation about toGeoJSON, and its precision argument.

**Comment by inkstak** [comment]
Hi, the build successfully passed on Travis, but the status doesn't show up in Github.
Is there any problem on my side ?

https://travis-ci.org/Leaflet/Leaflet/builds/514359440

**Comment by IvanSanchez** [comment]
Apparently https://travis-ci.org/Leaflet/Leaflet/builds/514359440 passed, so I see no problem there.

**Comment by IvanSanchez** [comment]
Changes to the documentation are not really needed, because https://github.com/Leaflet/Leaflet/pull/6375 is already merged.

**Comment by inkstak** [comment]
Thanks

**Pull request merged**
