### PR TITLE
Travis - run tests in Firefox

### PR DESCRIPTION
**Pull request by cherniavskii**
It is possible to run karma tests in Firefox with a virtual screen.
Do not merge before all errors in FF are fixed.

Tests which should be fixed:
- [x] Tooltip is opened when tapping on touch (#5869)
- [x] Tooltip is closed if not permanent when clicking on the map elsewhere on touch (#5869)
- [x] GridLayer number of 256px tiles loaded in synchronous animated grid @800x600px Loads 32, unloads 16 tiles zooming in 10-11 (#5844)
- [x] GridLayer number of 256px tiles loaded in synchronous animated grid @800x600px Loads 32, unloads 16 tiles zooming out 11-10
- [x] GridLayer configurable tile pruning Loads map, moves forth by 512 px, keepBuffer = 0 (#5844)
- [x] GridLayer configurable tile pruning Loads map, moves forth and back by 512 px, keepBuffer = 0 (#5844)

### CODE REVIEW

**Comment by cherniavskii** [comment]
Added also Chrome support

**Comment by mourner** [comment]
Looks like we'll only be able to turn this on once we sort out the failures on both browsers.

**Comment by cherniavskii** [comment]
@mourner yes

**Comment by cherniavskii** [comment]
Moved Chrome support to separate PR #5845

**Comment by ghybs** [comment]
I am glad you could solve some test issues by simply specifying the browser width in Travis config!

Now probably we should also improve those tests to positively specify the map container width, so that we do not rely on the browser width. For reference, these tests are:
- Marker.Drag drag in CSS scaled container drags a marker with mouse, compensating for CSS scale
- Canvas #events should not fire click when dragging the map on top of it
- Map.Drag mouse events change the center of the map

**Comment by cherniavskii** [comment]
> improve those tests to positively specify the map container width

Fair enough, but should it block this PR from merging?

> what exactly the env var DISPLAY=:99.0 is for?

Hmm, good question. It is required when using `xvbf` directly (see https://docs.travis-ci.com/user/gui-and-headless-browsers/).
But since I'm using `xvfb-run` wrapper, it seems unnecessary now.
I'll try to remove it :)

**Comment by cherniavskii** [comment]
@ghybs Yep, it works without `DISPLAY` env variable :) Thanks for your review! :)

**Comment by ghybs** [comment]
> should it block this PR from merging?

No, this was mainly for reference for future improvement, sorry I should have made it clearer.

**Comment by ghybs** [comment]
That is awesome! Thx @cherniavskii!

**Comment by cherniavskii** [comment]
@ghybs Thanks for your help ! :)

**Pull request merged**
