### PR TITLE
Create BundlingES6LeafletDocumentation.md

### LINKED ISSUE #5807: Need documentation for bundling ES6 Leaflet modules
Since the transformation to ES6 it should be possible to import only the needed parts of Leaflet and not the whole library.

Is there any documentation, examples, or whatnot, available for this kind of usage?

It would be extremely great to have a simple guide on this which would list inter-dependencies, what you should note when importing just a piece, and so forth. Like "to have this and that functionality, import this" and "if you import that, also this is going to get imported since that depends on it".

Any thoughts?

### PR DESCRIPTION
**Pull request by vishnugaruda246**
Created documentation for bundling ES6 Leaflet Modules

Fixes #5807

### CODE REVIEW

**Comment by vishnugaruda246** [comment]
@Ivan-Perez plz review

**Comment by Ivan-Perez** [comment]
I think you mean @IvanSanchez

**Comment by vishnugaruda246** [comment]
sorry for the confussion @Ivan-Perez

**Comment by shelar1423** [comment]
@jonkoops does this require any changes ? can i work on this issue too ?

**Comment by jonkoops** [comment]
Firstly, thanks for taking the effort to open up a PR. This seems to be a tutorial on how to use Leaflet with a bundler,  specifically WebPack. Although this is valuable information, I don't think it's particularly unique to Leaflet, or any other libraries for that matter.

This kind of documentation is already available [for WebPack](https://webpack.js.org/concepts/), and I think that we don't have to document this separately for Leaflet.

**Comment by jonkoops** [comment]
More background here: https://github.com/Leaflet/Leaflet/issues/5807#issuecomment-1783428989

**Pull request closed without merging**
