### PR TITLE
Make sure L.Control.removeLayer() doesn't raise an error if a layer n…

### PR DESCRIPTION
**Pull request by jieter**
…ot in the control is removed from it

Fixes issue #4486 reported by @theashyster in #4227

### CODE REVIEW

**Comment by theashyster** [comment]
I also tried this locally before posting the issue and this does not throw the error anymore, but has another side effect - it removes other layers from the LayerControl.

**Comment by jieter** [comment]
doh

**Comment by jieter** [comment]
Fixed now. I already added this check before, but since the test also succeeded without it, I removed it again. Time for coffee again.

**Comment by theashyster** [comment]
Thanks @jieter 
Damn tests :smiley:

**Pull request merged**
