### PR TITLE
Fix for issue #5116

### PR DESCRIPTION
**Pull request by iZucken**
As this filters out custom inputs created from property names (supposedly using innerHTML), they still will become unusable whenever _update() is fired on control.
I believe that this is a different issue coming from design of a module.

### CODE REVIEW

**Comment by iZucken** [comment]
@perliedman, Please, check line #145 - array gets flushed there. Also, do note that flush rather than in e.g. splice is needed, because after that in _update it gets repopulated by calling _addItem (line #272) on every layer again. That is also the cause for unbinding of events on DOM blocks inside captions.

**Comment by perliedman** [comment]
@iZucken ah, sorry, missed that line.

Good analysis, that explains the issue clearly. So, given this, I interpret this as even if you sort of fixed the issue, it's still not really meaningful to have `input`s in the labels, at least not if you want to attach event handlers to them?

**Comment by iZucken** [comment]
It can be. I can see many applications where a plain statement of this fact in documentation could suffice to a degree. Knowing that, user will just have to rebind his events after "destructive" operations.

**Comment by iZucken** [comment]
I rebased commits to local master, but it appears that one cannot change head branch of a request (probably not truth). Should I create a new one (and close this)?

**Pull request closed without merging**
