### PR TITLE
Added FeatureCollection to geometryToLayer function

### PR DESCRIPTION
**Pull request by franbenz**
A GeoJSON object with the type "FeatureCollection" can now be transformed to a layer.

### CODE REVIEW

**Comment by IvanSanchez** [comment]
This functionality is already in 1.0.0, and I'm not really sure it's really needed to be backported into stable at this point. :-/

**Comment by franbenz** [comment]
I needed this on the stable branch since I'm using leaflet as an angular directive with a project that depends on 0.7.x (https://github.com/tombatossals/angular-leaflet-directive/blob/master/bower.json#L18)

**Comment by mourner** [comment]
This only affects nested feature collections, right? Because `addData` handles the top level feature collection case already.

**Comment by franbenz** [comment]
No, in my application I got an "Invalid GeoJSON object" error when passing a Feature Collection object to geometryToLayer(in the stable branch), that's why I needed the patch I'm adding.

**Comment by franbenz** [comment]
Any suggestions with this issue?

**Comment by kentr** [comment]
@franbenz Are you passing a GeoJSON string for `data` in the layer definition?  If so, that may be the cause of the error.  I'm also using ui-leaflet, and it caused this error for me.

I question whether `geometryToLayer()` is supposed to receive `Feature` or `FeatureCollection` objects, rather than exclusively [`Geometry` objects](http://geojson.org/geojson-spec.html#geometry-objects).

For me, the solution was to create the layer definition similar to this:

```
var newLayerDef = {
  name: 'POI',
  type: 'geoJSONShape',
  visible: true,
  data: JSON.parse('{"type": "FeatureCollection", "features": [ ... ]}'),
  layerOptions: {
    pointToLayer: function (feature, latlng) {
      return L.marker(latlng);
    }
  },
};
```

**Comment by mourner** [comment]
Closing because we just released 1.0 and minor issues in 0.7.x are unlikely to be fixed.

**Pull request closed without merging**
