### PR TITLE
Added Leaflet.CountrySelect plugin

### PR DESCRIPTION
**Pull request by ahalota**

### CODE REVIEW

**Comment by IvanSanchez** [comment]
@ahalota I fing the plugin a bit buggy - I cannot scroll the drop-down list, or drag the scrollbar (events get passed to the map). Can you fix that?

**Comment by jieter** [comment]
I can do both in the drop-down without a problem...

http://ahalota.github.io/Leaflet.CountrySelect/demo.html

**Comment by IvanSanchez** [comment]
Apparently it works in chrome but fails in firefox.

**Comment by ahalota** [comment]
@IvanSanchez What do you mean by drag the scrollbar?

As for scrolling the drop down list - When I run it in firefox, I can scroll the list with the key up/down buttons. The change event is only fired once you hit 'enter' however. I believe this is just part of how firefox handles change events on `select` elements

> When the element loses focus after its value was changed, but not commited (e.g. after editing the value of &lt;textarea&gt; or &lt;input type="text"&gt;

[MDN change - event reference](https://developer.mozilla.org/en-US/docs/Web/Events/change)

**Comment by ahalota** [comment]
I fixed the clicking, it shouldn't act as strange in Firefox or IE anymore.

I am still working on getting the scrollwheel to play nice. I am having trouble stopping leaflet from 'stealing' the scroll event from my dropdown in Firefox and IE. I will see what I can do about that. Thank you for the feedback.

**Pull request merged**
