### PR TITLE
Stop animation before destroy map

### PR DESCRIPTION
**Pull request by dnepromell**
If create and remove map very quickly, animation stuck in a loop with exception:

"TypeError: Cannot read property _leaflet_pos of undefined\n    at getPosition (http://local/js/app/vendor/leaflet-1.2.0.js?t=:2713:12)\n    at NewClass._getMapPanePos (http://local/js/app/vendor/leaflet-1.2.0.js?t=:4308:10)\n    at NewClass.containerPointToLayerPoint (http://local/js/app/vendor/leaflet-1.2.0.js?t=:3891:39)\n    at NewClass.containerPointToLatLng (http://local/js/app/vendor/leaflet-1.2.0.js?t=:3905:25)\n    at NewClass._update (http://local/js/app/vendor/leaflet-1.2.0.js?t=:5346:9)\n    at NewClass.fire (http://local/js/app/vendor/leaflet-1.2.0.js?t=:588:11)\n    at NewClass._onPanTransitionStep (http://local/js/app/vendor/leaflet-1.2.0.js?t=:4415:8)\n    at NewClass.fire (http://local/js/app/vendor/leaflet-1.2.0.js?t=:588:11)\n    at NewClass._runFrame (http://local/js/app/vendor/leaflet-1.2.0.js?t=:2904:8)\n    at NewClass._step (http://local/js/app/vendor/leaflet-1.2.0.js?t=:2890:9)"

### CODE REVIEW

**Comment by mourner** [comment]
Thank you!

**Comment by aaronplanell** [comment]
Hello!!!

First of all, thanks @dnepromell for your _Pull Request_ and thanks @mourner for your job. 

Just a couple of things:
- The code is not released in NPM. I downloaded the last version (```v1.2.0```) and I've got the same problem :cry: . I modified the code in ```node_modules\leaflet\dist\leaflet-src.js``` with these changes.
- But, I'd got a new problem with the ```_animateZoom``` function in these two lines: 
   - ```addClass(this._mapPane, 'leaflet-zoom-anim');```
   - ```this.fire('zoomanim', {  ... });```

This is a problem if you're redirecting to another page if the transition is running with a ```flyTo``` with animated ```true```.

I was thinking about creating a new _Pull Request_ to modify the function this way:
```
	_animateZoom: function (center, zoom, startAnim, noUpdate) {

		if(!this._mapPane) return;

		Bla, bla, bla...
```

What do you think about it? Should I make the _Pull Request_?

Best regards and thanks for your attention.
Aaron Planell

**Comment by perliedman** [comment]
@aaronplanell if this is a new issue, please open a new issue to discuss it.

**Comment by aaronplanell** [comment]
Hello @perliedman ,

Thanks for your answer. I will open a new pull request fixing the issue. Anyway, it was surprising to me to have seen that the master branch has different code than the NPM package :package: :disappointed: 

Best regards.

**Comment by aaronplanell** [comment]
Hello @perliedman !

OK. I understand it. Thanks a lot for your work! :smile: 

Best regards.

**Pull request merged**
