### PR TITLE
Ensure that element is a child before removing it from the parent

### LINKED ISSUE #8432: remove() doesn't check that parent has that child causing an exception
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Remove function causes an exception when using Leaflet.markercluster.

`function remove(el) {
  	var parent = el.parentNode;
  	if (parent) {
  		parent.removeChild(el);
  	}
  }`

When zooming in on a cluster that contains multiple markers at the same location I sometimes get an exception:

`Uncaught DOMException DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at _remove (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:2136:1)
    at _removeIcon (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:7240:1)
    at onRemove (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:7088:1)
    at removeLayer (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:6319:1)
    at removeLayer (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:6459:1)
    at removeLayer (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:6593:1)
    at <anonymous> (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1801:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1828:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursivelyRemoveChildrenFromMap (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1782:1)
    at _animationZoomIn (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1257:1)
    at _mergeSplitClusters (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1138:1)
    at _zoomEnd (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:978:1)
    at fire (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:624:1)
    at _moveEnd (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:3996:1)
    at _onZoomTransitionEnd (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:4463:1)
    at _catchTransitionEnd (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:4381:1)
    at handler (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:2555:1)`

### Expected behavior

The function should check that the parent contains this child before attempting to remove

### Current behavior

Exception

### Minimal example reproducing the issue

_No response_

### Environment

- Leaflet version: 1.8.0
- Browser (with version): Chrome
- OS/Platform (with version): Mac 12.5.1

### PR DESCRIPTION
**Pull request by ShivangMishra**
Closes #8432

### CODE REVIEW

**Comment by jonkoops** [comment]
Does this prevent some kind of error? Is there an issue related to this PR that has more information?

**Comment by ShivangMishra** [comment]
> Does this prevent some kind of error? Is there an issue related to this PR that has more information?

issue #8432  I mentioned in PR title too

**Review by jonkoops — CHANGES_REQUESTED** [review]
Can you add some tests to ensure this is covered?

**Comment by jonkoops** [comment]
@ShivangMishra when opening a PR try to give it a descriptive title that makes it easy to understand what your change does. This helps us compile a changelog that makes sense to users when we do a release.

Also if there is an existing issue you can use [keywords in your description](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to ensure it is linked properly.

**Comment by jonkoops** [comment]
I'm closing this PR as I am not convinced this actually resolves the issue it relates to.

**Pull request closed without merging**
