### PR TITLE
Website Redesign

### PR DESCRIPTION
**Pull request by mourner**
Master ticket for the redesign. Looks like this: http://mourner.github.io/Leaflet
Remaining stuff:

- [x] add actual links to logos
- [x] revise visual hierarchy (e.g. too much color variation between headings)
- [x] update docs table styling for mobile
- [x] other mobile adjustments (e.g. tagline too big)
- [x] more prominent section headings on the docs page

Dynamic ToC:

- [x] dynamic ToC on the plugins page
- [ ] make docs categories clickable as well
- [ ] fix not being able to click docs permalink icons with certain window width
- [ ] add "to the top" link?

Revising logo list:

- [x] remove Hipmunk (uses GMaps now)
- [x] add Facebook
- [x] add Flickr
- [x] add European Commission
- [x] add Data.gov
- [x] add National Park Service
- [x] add Etsy
- [x] add IGN.com?
- [x] anything else?

Copy edits:

- [x] simplify features section wording
- [x] blog post about redesign

cc @rowanhogan

### CODE REVIEW

**Comment by mourner** [comment]
@rowanhogan question, are you opposed to the green headings? I'm thinking of bringing them back at least just for the Docs page, where they help skimming the page a lot.

**Comment by jieter** [comment]
I also liked the green headings. It's nice to have a visual boundary between the topics.

**Comment by rowanhogan** [comment]
I prefer the visual design without the green, but I agree it does make them blend into the background a bit.

I initially tried quite a few different variations for these headings, settling for a horizontal rule beneath them in the earlier version which helped with scanning. See below screenshots from my earlier designs for both how they sit normally, and then how they appear when scrolled to (`:target`).

Normal:

normal

Target:

target

**Comment by mourner** [comment]
Yeah, maybe we could go by with just thick borders:

image

**Comment by mourner** [comment]
@rowanhogan I'd love you to take on the following tasks:

- updating logos per the list above
- dynamic ToC on the plugins page (same as on docs)

**Comment by mourner** [comment]
@rowanhogan made some heading style adjustments, please check if they look good to you.

**Comment by jieter** [comment]
All code blocks now have disables x/y scroll bars...

**Comment by mourner** [comment]
@jieter are you sure? They work fine for me.

**Comment by jieter** [comment]
2015-07-01-122241_1035x358_scrot

**Comment by mourner** [comment]
@jieter wow, what's the browser / OS?

**Comment by mourner** [comment]
Ah, @IvanSanches fixed this :)

**Comment by jieter** [comment]
For sake of completeness: 43.0.2357.81 (Developer Build) Ubuntu 14.04 (64-bit)

**Comment by mourner** [comment]
@rowanhogan thanks so much! This looks stunning. Now just a few things to fix in the sidebar ToC and we're done with the redesign.

**Comment by mourner** [comment]
TADAAAA!!!

**Comment by jieter** [comment]
wow

**Comment by rowanhogan** [comment]
Woohoo! :tada:

**Comment by tdaubs** [comment]
Nice work! Keep it up!

**Pull request merged**
