### PR TITLE
Remove dot in signature

### PR DESCRIPTION
**Pull request by WebSnke**

### CODE REVIEW

**Comment by jonkoops** [comment]
Thanks for opening a PR, but I see no value in landing this change.

**Comment by WebSnke** [comment]
> Thanks for opening a PR, but I see no value in landing this change.

But that's the correct way to sign a letter.

Yours truly,
WebSnke

**Comment by WebSnke** [comment]
[This](https://chat.openai.com/share/96c7adae-55fb-4d01-a3f8-1ac69c89749f) is what ChatGPT thinks.

**Comment by jonkoops** [comment]
I really don't care what ChatGTP thinks, it's not a reliable source of information. We do not accept AI generated contributions because they are of low quality and waste out time.

**Comment by WebSnke** [comment]
> I really don't care what ChatGTP thinks, it's not a reliable source of information. We do not accept AI generated contributions because they are of low quality and waste our time.

Ok, then look at [this](https://www.indeed.com/career-advice/career-development/ways-to-sign-a-letter).
This source confirms that you would not end it with a dot.

**Pull request closed without merging**
